### ISSUE TITLE
raspberrypi-ui-mods fails when running apt-get dist-upgrade when user/group pi:pi is removed

### ISSUE THREAD

**Issue by antoniosk** [RPi-Distro/repo#10]
I am running Raspbian Jessie. According to this article https://www.raspberrypi.org/blog/latest-raspbian-update/, I run sudo apt-get update and sudo apt-get dist-upgrade.

The upgrade failed because I had removed the default user pi. The script in file /var/lib/dpkg/info/raspberrypi-ui-mods.postinst assumes that user pi exist (line 42), as it's home folder (line 11).

Workaround: I created again a user pi using useradd and it's home folder sudo apt-get dist-upgrade succeeded.

**Comment by XECDesign** [comment]
Thanks, will be addressed in the next release.
