### ISSUE TITLE
Installing DigiKam package / PulseAudio drivers results in audio sync issues in Chromium browser

### ISSUE THREAD

**Issue by rsfitz** [RPi-Distro/repo#101]
**Description:**
Installing the currently published digiKam package will result in audio sync issues when using Chromium browser to play YouTube videos.

**Build:**
Raspbian Stretch - January 2018 - Kernel 4.9

**Steps To Reproduce:**

1. Install digiKam (sudo apt-get install digikam or pulseaudio)
2. Reboot pi, launch Chromium play YouTube video 

**Note:** Symptom were experienced when using the Analog (PCM) output

**Comment by XECDesign** [comment]
I don't believe this is caused by any modifications we have made. It's best to report issues like this upstream to pulseaudio.
