### ISSUE TITLE
Where is the source code of the welcome tool?

### ISSUE THREAD

**Issue by cwfoo** [RPi-Distro/repo#113]
On a new install, Raspbian Stretch presents the user with a welcome wizard that says:

```
Welcome to the Raspberry Pi Desktop!

Before you start using it, there are a few things to set up.

Press 'Next' to get started.
```

This tool helps the user set the country, change the default password, and check for updates.

Where can I find the source code of this tool?

**Comment by XECDesign** [comment]
https://github.com/raspberrypi-ui/piwiz
