### ISSUE TITLE
Please update VDR to 2.4.0

### ISSUE THREAD

**Issue by ajbathe** [RPi-Distro/repo#115]
Hello,
I installed Raspbian stretch lite and worked out a tv server for Kodi with vdr. I discovered that the old version 2.2.0 in your Raspbian Distribution is quite old and does not work with DVB-T2 and HEVC265. But the version 2.4.0 does it quite good. Could you update the package vdr please?
The stable version 2.4.0 is available since months.
https://www.vdr-portal.de/forum/index.php?thread/131790-announce-vdr-stable-version-2-4-0/
thanx a lot
Andreas

**Comment by XECDesign** [comment]
This one seems to have resolved itself with the release of buster >.>
