### ISSUE TITLE
gqrx doesn't work, dumps core

### ISSUE THREAD

**Issue by akkana** [RPi-Distro/repo#125]
With an SDR radio dongle plugged in:
sudo apt-get install gqrx-sdr
gqrx

gives:linux; GNU C++ version 6.2.0 20161010; Boost_106100; UHD_003.009.005-0-unknown

libEGL warning: DRI3: failed to query the version
libEGL warning: DRI2: failed to authenticate
Controlport disabled
No user supplied config file. Using "default.conf"
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya
FM demod gain: 1.52789
IQ DCR alpha: 1.04166e-05
Using audio backend: auto
BookmarksFile is /home/akkana/.config/gqrx/bookmarks.csv
*** Error in `gqrx': corrupted double-linked list: 0x01ed0b68 ***
zsh: abort (core dumped)  gqrx

This is apparently a well-known problem: see
https://www.reddit.com/r/RTLSDR/comments/7xvkm1/gqrx_doesnt_work_from_raspbian_repos/
which points to a different place to get an ARM binary:
http://gqrx.dk/download/gqrx-sdr-for-the-raspberry-pi

Could the Raspbian distros update to do whatever that gqrx page is doing? It seems to work, or at least it brings up a window and doesn't dump core (I haven't figured out how to use it yet).

**Comment by XECDesign** [comment]
`gqrx-sdr` doesn't come from our repo (archive.raspberrypi.org). However, if you a tested source package (`.dsc` and associated filed), then we could add it.
