### ISSUE TITLE
Raspberry Touch ui won´t start

### ISSUE THREAD

**Issue by Drakogol** [RPi-Distro/repo#126]
Hi,
I somehow don´t find any solutions to this maybe here i can get help. My 3D-Printer has a Raspberry 3 B connected to it with Octoprint installed. Over the web Interface it all works fine. But now i want to upgrade the whole thing with a touch screen.
I went with this tutorial: https://plastikjunkies.de/touchscreen-fuer-octoprint-raspberry-pi/
Except i did buy a different touchscreen as mentioned there, i did as it stands there. But as I´m trying to start the chromium-browser with putty i get this.

xinit chromium-browser

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
Current Operating System: Linux octopi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l
Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1024 bcm2708_fb.fbheight=600 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=e100d113-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
Build Date: 18 October 2017  04:55:30PM
xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support)
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/pi/.local/share/xorg/Xorg.0.log", Time: Thu Feb 21 18:00:11 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/home/pi/.local/share/xorg/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

Hope this helps 

apt-cache policy chromium-browser
chromium-browser:
  Installed: 65.0.3325.181-0+rpt4
  Candidate: 65.0.3325.181-0+rpt4
  Version table:
 *** 65.0.3325.181-0+rpt4 500
        500 http://archive.raspberrypi.org/debian stretch/main armhf Packages
        100 /var/lib/dpkg/status

And this is the log i hope

[  1998.802]
X.Org X Server 1.19.2
Release Date: 2017-03-02
[  1998.803] X Protocol Version 11, Revision 0
[  1998.803] Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
[  1998.803] Current Operating System: Linux octopi 4.14.79-v7+ #1159 SMP Sun N$
[  1998.803] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1024 bcm27$
[  1998.803] Build Date: 18 October 2017  04:55:30PM
[  1998.803] xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support$
[  1998.803] Current version of pixman: 0.34.0
[  1998.803]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  1998.803] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1998.804] (==) Log file: "/home/pi/.local/share/xorg/Xorg.0.log", Time: Thu $
[  1998.805] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1998.805] (==) No Layout section.  Using the first Screen section.
[  1998.805] (==) No screen section available. Using defaults.
[  1998.805] (**) |-->Screen "Default Screen Section" (0)
[  1998.805] (**) |   |-->Monitor "<default monitor>"
[  1998.807] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.
[  1998.807] (**) |   |-->Device "touchscreen"
[  1998.807] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1998.807] (==) Automatically adding devices
[  1998.807] (==) Automatically enabling devices
[  1998.807] (==) Automatically adding GPU devices
[  1998.807] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1998.807] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[  1998.807]    Entry deleted from font path.
[  1998.807] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1998.807]    Entry deleted from font path.
[  1998.807] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1998.807]    Entry deleted from font path.
[  1998.807] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1998.807]    Entry deleted from font path.
[  1998.807] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1998.807]    Entry deleted from font path.
[  1998.808] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1998.808]    Entry deleted from font path.
[  1998.808] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1998.808]    Entry deleted from font path.
[  1998.808] (==) FontPath set to:
        built-ins
[  1998.808] (==) ModulePath set to "/usr/lib/xorg/modules"
[  1998.808] (II) The server relies on udev to provide the list of input device$
        If no devices become available, reconfigure udev or disable AutoAddDevi$
[  1998.808] (II) Loader magic: 0x1fbf40
[  1998.808] (II) Module ABI versions:
[  1998.808]    X.Org ANSI C Emulation: 0.4
[  1998.808]    X.Org Video Driver: 23.0
[  1998.808]    X.Org XInput driver : 24.1
[  1998.808]    X.Org Server Extension : 10.0
[  1998.811] (--) using VT number 2

[  1998.812] (II) systemd-logind: logind integration requires -keeptty and -kee$
[  1998.812] (II) no primary bus or device found
[  1998.812] (II) LoadModule: "glx"
[  1998.813] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1998.821] (II) Module glx: vendor="X.Org Foundation"
[  1998.821]    compiled for 1.19.2, module version = 1.0.0
[  1998.821]    ABI class: X.Org Server Extension, version 10.0
[  1998.821] (II) LoadModule: "fbdev"
[  1998.822] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[  1998.822] (II) Module fbdev: vendor="X.Org Foundation"
[  1998.822]    compiled for 1.19.0, module version = 0.4.4
[  1998.822]    Module class: X.Org Video Driver
[  1998.822]    ABI class: X.Org Video Driver, version 23.0
[  1998.822] (II) FBDEV: driver for framebuffer: fbdev
[  1998.823] (EE)
Fatal server error:
[  1998.823] (EE) xf86OpenConsole: Cannot open virtual console 2 (Permission de$
[  1998.823] (EE)
[  1998.823] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[  1998.823] (EE) Please also check the log file at "/home/pi/.local/share/xorg$
[  1998.823] (EE)
[  1998.824] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[  1998.824] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[  1998.824] (EE) Server terminated with error (1). Closing log file.

Im new to this whole thing so something simple as: Do this ... or this....
would be much appreciated
Thank you in advance

**Comment by XECDesign** [comment]
The forum would be a more appropriate place to post this.

https://www.raspberrypi.org/forums/index.php
