### ISSUE TITLE
Please add Movian 

### ISSUE THREAD

**Issue by csgabe** [RPi-Distro/repo#128]
Please add Movian application package for alpine linux:
https://github.com/andoma/movian
I think it needs OpenGL.

**Comment by XECDesign** [comment]
Alpine? We don't have anything at all to do with Alpine Linux, we only support Raspbian.

**Comment by csgabe** [comment]
Sorry, I meant Raspbian.

**Comment by XECDesign** [comment]
Doesn't look like it has been packaged up properly:
```
debuild: fatal error at line 660:
cannot find readable debian/changelog anywhere!
```
