### ISSUE TITLE
arm7l distro in Raspbian missing module (usb_f_fs ) no write access to configFS /sys/kernel/config/ 

### ISSUE THREAD

**Issue by dernyn** [RPi-Distro/repo#129]
can we natively include the module (usb_f_fs ) in the mainline arm7l distro;
This was there before but has been removed.

I dont want to compile my own just to get custom USB gadgets working.

**Comment by XECDesign** [comment]
Kernel issues requests should go here:
https://github.com/raspberrypi/linux/issues/
