### ISSUE TITLE
Chromium crash after multiple videos

### ISSUE THREAD

**Issue by davidmmgo** [RPi-Distro/repo#140]
Hi,

I have a script that plays a new video when the previous one ends, looping forever.
However, after a few dozen iterations (roughly around 40 to 50 - it seems to vary depending on the video resolution), the tab crashes unexpectedly. 
On the terminal output, it displays the following message:
`[12777:12824:0626/174427.698705:WARNING:audio_sync_reader.cc(87)] ASR: No room in socket buffer.:Broken pipe (32)`

This only happens with MP4 files, and with every mp4 file I've tried so far. Webm files work fine.

My setup:
 **Hardware:** RaspberryPi 3B
 **OS:** Raspbian 10 (buster)
 **Kernel:** Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:14 BST 2019 armv7l GNU/Linux
 **Chromium:** 74.0.3729.157 Built on Raspbian , running on Raspbian 10

Here's my test script: 

`window.onload = function () {

    const videoUrl = 'assets/myvideo';
    const videoExt = '.mp4';
    const videoTagID = 'video_place';
    const videoTag = document.getElementById(videoTagID);
    let attemptCount = 0;

    function playVideo() {
        console.log('------------ ATTEMPT # ' + attemptCount);
        videoTag.src = videoUrl + videoExt;
        videoTag.play()
            .then(() => { console.log('SUCCESS ON ATTEMPT #' + attemptCount); })
            .catch(() => { console.log('ERROR ON PROMISE ATTEMPT #' + attemptCount); });
    }

    videoTag.onended = function () {
        console.log('ENDED #' + attemptCount++);
        playVideo();
    };
    
    playVideo();
};
`
And here's a sample from the log I gathered:
[chromium.log](https://github.com/RPi-Distro/repo/files/3346053/chromium.log)

I suspect this might be a bug within Chromium for raspberry, since it doesn't happen on Ubuntu 18.04. Also, the very same script works fine on Firefox ESR on the pi.

This same issue also happened on Chromium 72, but it would freeze the entire browser.
The issue was not present on Chromium 65.0.3325.181.

Let me know if there's any other info I need to provide.

Thanks!
David

**Comment by XECDesign** [comment]
Are you still seeing it with v84? Sorry to leave this hanging for that long.
