### ISSUE TITLE
Buster libssl-dev depends on libssl1.1 version 1.1.0j

### ISSUE THREAD

**Issue by fayelund** [RPi-Distro/repo#141]

**Comment by fayelund** [comment]
libssl-dev on buster depends on libssl1.1 version 1.1.0j but 1.1.1c is installed.

**Comment by XECDesign** [comment]
Looks okay from here.

Could you please post the output of `sudo apt update && sudo apt policy`?

**Comment by fayelund** [comment]
Yeah, found a faulty puppet rule messing up sources.list to stretch. My bad, sorry for bothering with this.
