### ISSUE TITLE
libttspico0 & libttspico-utils missing from raspbian buster - both are in debian buster

### ISSUE THREAD

**Issue by jerrm** [RPi-Distro/repo#143]
Packages are in Debian but not Raspbian - https://packages.debian.org/buster/libttspico-utils.  

Can they be added to Raspbian?

**Comment by XECDesign** [comment]
Please note this repo is for archive.raspberrypi.org packages, not general Raspbian packages (raspbian.raspberrypi.org). The Raspbian repo isn't managed by us and issues should be reported here - https://bugs.launchpad.net/raspbian/
