### ISSUE TITLE
Buster: unable to start CLISP after installing package

### ISSUE THREAD

**Issue by RonaldCole** [RPi-Distro/repo#146]
On a RPi 3B+ with fresh full Buster install on a 32GB Samsung EVO Plus sdcard:

pi@raspberrypi:~ $ clisp
Warning: reserving address range 0x48060000...0xafffffff that contains memory mappings. clisp might crash later!
Memory dump:
  0x10000 - 0x182fff
  0x192000 - 0x193fff
  0x194000 - 0x1adfff
  0x1ae000 - 0x1b0fff
  0xfcd000 - 0xfedfff
  0x48000000 - 0x4805ffff
  0x76634000 - 0x768adfff
  0x768ae000 - 0x76aadfff
  0x76aae000 - 0x76be5fff
  0x76be6000 - 0x76bf5fff
  0x76bf6000 - 0x76bf7fff
  0x76bf8000 - 0x76bf8fff
  0x76bf9000 - 0x76bfbfff
  0x76bfc000 - 0x76d65fff
  0x76d66000 - 0x76d74fff
  0x76d75000 - 0x76d76fff
  0x76d77000 - 0x76d77fff
  0x76d78000 - 0x76d79fff
  0x76d7a000 - 0x76d89fff
  0x76d8a000 - 0x76d8afff
  0x76d8b000 - 0x76d8bfff
  0x76d8c000 - 0x76d8efff
  0x76d8f000 - 0x76d9efff
  0x76d9f000 - 0x76d9ffff
  0x76da0000 - 0x76da0fff
  0x76da1000 - 0x76da2fff
  0x76da3000 - 0x76db1fff
  0x76db2000 - 0x76db2fff
  0x76db3000 - 0x76db3fff
  0x76db4000 - 0x76dbafff
  0x76dbb000 - 0x76dcafff
  0x76dcb000 - 0x76dcbfff
  0x76dcc000 - 0x76dccfff
  0x76dcd000 - 0x76df3fff
  0x76df4000 - 0x76e64fff
  0x76e65000 - 0x76e73fff
  0x76e74000 - 0x76e74fff
  0x76e75000 - 0x76e75fff
  0x76e76000 - 0x76e93fff
  0x76e94000 - 0x76ea3fff
  0x76ea4000 - 0x76ea5fff
  0x76ea6000 - 0x76ea6fff
  0x76ea7000 - 0x76ec3fff
  0x76ec4000 - 0x76ed2fff
  0x76ed3000 - 0x76ed3fff
  0x76ed4000 - 0x76ed4fff
  0x76ed5000 - 0x76f0afff
  0x76f0b000 - 0x76f1afff
  0x76f1b000 - 0x76f1bfff
  0x76f1c000 - 0x76f1ffff
  0x76f20000 - 0x76f20fff
  0x76f26000 - 0x76f27fff
  0x76f28000 - 0x76f36fff
  0x76f37000 - 0x76f37fff
  0x76f38000 - 0x76f38fff
  0x76f39000 - 0x76f3cfff
  0x76f3d000 - 0x76f4bfff
  0x76f4c000 - 0x76f4cfff
  0x76f4d000 - 0x76f4dfff
  0x76f4e000 - 0x76f6dfff
  0x76f70000 - 0x76f76fff
  0x76f77000 - 0x76f79fff
  0x76f7a000 - 0x76f7dfff
  0x76f7e000 - 0x76f7efff
  0x76f7f000 - 0x76f7ffff
  0x7ebff000 - 0x7ec1ffff
  0x7ecd1000 - 0x7ecd1fff
  0x7ecd2000 - 0x7ecd2fff
  0x7ecd3000 - 0x7ecd3fff
  0xffff0000 - 0xffff0fff
Cannot map memory to address 0xaff73000 .
[/build/clisp-e5HBJM/clisp-2.49.20180218+really2.49.92/src/spvw_mmap.d:526] errno = 12 (:ENOMEM): Cannot allocate memory.
/usr/lib/clisp-2.49.92/base/lisp.run: not enough memory for initialization

Is it a problem with the package being built on a system with a hardened toolchain?  I'm not familiar with the details of building clisp on a Raspberry Pi to help debug this, but I gotta think that I'm not the only one trying to use it on Buster.  I didn't try clisp on Stretch.

**Comment by XECDesign** [comment]
Please note clisp does not come from archive.raspberrypi.org, which is what this issue tracker is for.

Raspbian has its own bug tracker here https://bugs.launchpad.net/raspbian/.

I did a little bit of testing:
Pi 3B+ running stretch - works
Pi 3B+ running buster - fails
Pi 4 running buster - works

So it looks like it broke on the 3B+ somewhere after here https://salsa.debian.org/common-lisp-team/clisp/blob/debian/1%252.49.20180218+really2.49.92-3/debian/changelog#L180

I wouldn't recommend opening the issue in the appropriate tracker.
