### ISSUE TITLE
Docker not working on buster at all!

### ISSUE THREAD

**Issue by AquaMCU** [RPi-Distro/repo#150]
Describe the bug
When starting, docker crashes with:
docker: Error response from daemon: unable to find "net_prio" in controller set: unknown.

!!! INFO
Docker version 18.09.1
Bug is fixed in docker-containerd in Feb this year. Please update docker so we will have a fix !

Link to FIX:
containerd/containerd#3048

To reproduce
Install docker:
sudo apt-get install docker docker-compose

Run:
docker run hello-world

Output:
docker: Error response from daemon: unable to find "net_prio" in controller set: unknown.

This still happens 100%. I just apt-get updated and upgraded today ...

Expected behaviour
docker starts and says HELLO WORLD ;)

Actual behaviour
docker: Error response from daemon: unable to find "net_prio" in controller set: unknown

System
Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

    Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
    Pi 4
    Which OS and version (cat /etc/rpi-issue)?
    Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 175dfb027ffabd4b8d5080097af0e51ed9a4a56c, stage4

Logs
If applicable, add the relevant output from dmesg or similar.

Additional context
Please do not add additional info like in the other tickets. That is just confusing and leads to closing this ticket. Seriously. We just need to update docker and .... BOOM problem solved. And yes, you can update your repos and install docker manually, but is that how we want to use a distribution?

**Comment by XECDesign** [comment]
I'm not having much luck with this.

I've updated golang-github-containerd-cgroups to the version you linked, backported golang-github-opencontainers-specs from bullseye and rebuilt docker.io, but the problem still occurs.

**Comment by XECDesign** [comment]
Ah, after restarting the docker service it seems to work. I'll push the update a bit later.

**Comment by XECDesign** [comment]
Added to the 'untested' component of archive.raspberrypi.org (/etc/apt/sources.list.d/raspi.list). If you can give it a spin and confirm it doesn't break anything else, I can put it into 'main'.

Information on how to use 'untested' here:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=249650&p=1524254#p1524254

**Comment by AquaMCU** [comment]
Hi. I am on a business trip right now, when I am home, I give it a ride. 

Thanks for the help°!

**Comment by AquaMCU** [comment]
Hmm. 

I have installed a new SD card and installed the untested repo.

Issue is fixed although docker --version still gives me the 18.09.1 build 4c52b90

INFO: I have not tested for any other docker related regressions.

Thank you! Do you have an estimate when this will be available in the official repo?

Oliver

**Comment by XECDesign** [comment]
The fix isn't in docker, but in a build dependency of docker, so the version wouldn't change.

Ill probably push it to 'main' today.

**Comment by XECDesign** [comment]
Should've made it into the main repo yesterday.
