### ISSUE TITLE
Add ntfs-3g

### ISSUE THREAD

**Issue by DougieLawson** [RPi-Distro/repo#151]
I don't know if this is the right place to report this. But can you add ntfs-3g to the default pre-installed collection of packages in Raspbian.

It will reduce forum traffic for folks connecting NTFS drives.

**Comment by XECDesign** [comment]
Already a part of the next release:
https://github.com/RPi-Distro/pi-gen/blob/master/export-noobs/00-release/files/release_notes.txt#L3

**Comment by DougieLawson** [comment]
Thank you.
