### ISSUE TITLE
libcollada-dom2.4-dp0 not rebuild in Buster

### ISSUE THREAD

**Issue by gallaert** [RPi-Distro/repo#162]

**Comment by gallaert** [comment]
libcollada-dom2.4-dp0 has been build for Raspbian 9 not 10. The package has still dependencies to libboost-filesystem1.58.0 and libboost-system1.58.0.
I have rebuild collada-dom using pbuilder on Raspbian 10 without any issue. The dependencies are now correct (Boost 1.67)

**Comment by XECDesign** [comment]
```
libcollada-dom2.4-dp0:
  Installed: (none)
  Candidate: 2.4.4+ds1-2
  Version table:
     2.4.4+ds1-2 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```

Seems to have been resolved since.
