### ISSUE TITLE
kdeconnect - it should be possible to only install kdeconnect-cli

### ISSUE THREAD

**Issue by Mannshoch** [RPi-Distro/repo#168]
I use this system without a graphic interface. If you try to install kdeconnect, a huge amount of packages will get installed.

Please allow to install only kdeconnect-cli.

**Comment by XECDesign** [comment]
This issue tracker is for packages in archive.raspberrypi.org repo. We don't package or modify kdeconnect in any way.

https://www.debian.org/Bugs/
