### ISSUE TITLE
targetcli-fb unusable

### ISSUE THREAD

**Issue by ulecrivain** [RPi-Distro/repo#171]
Hello,
Given that the current raspberrypi kernel doesn't include required modules for targetcli-fb according to [issue #2184](https://github.com/raspberrypi/linux/issues/2184):
shouldn't the package be deleted from the repository or marked broken since it can't be used ?
Thanks.

**Comment by XECDesign** [comment]
As with https://github.com/RPi-Distro/repo/issues/172, it's not something we have any control over.
