### ISSUE TITLE
zstd causes Bus error

### ISSUE THREAD

**Issue by jfikar** [RPi-Distro/repo#179]
There is a problem with zstd package in recent Raspberry Pi OS (armhf). When trying to compress anything with zstd, it generates a Bus error and stops. The version is zstd-1.3.8+dfsg-3+rpi1. It worked in the past. I'm using RPi4.

```
dd if=/dev/urandom bs=1M count=10 | zstd > test.zst 
Bus error
```

Debian 10.4 zstd-1.3.8+dfsg-3 works fine both armhf and aarch64. Experimental Raspberry Pi OS aarch64 works as well, version zstd-1.3.8+dfsg-3.

**Comment by jfikar** [comment]
The Bus error occurs when compression level is between 1 and 4 (default compression level without specifying anything is 3). From 5 up, there is no error. Decompression is also fine.

zstd -3 file.... crash
zstd -5 file.... OK

**Comment by XECDesign** [comment]
Seems to be resolved in Bullseye?

**Comment by jfikar** [comment]
I've just checked, Bullseye has the version 1.4.8 of zstd and the problem is gone.

**Comment by XECDesign** [comment]
Many thanks for confirming.
