### ISSUE TITLE
Raspian wifi config

### ISSUE THREAD

**Issue by whyvas** [RPi-Distro/repo#18]
It would be a fantastic feature to have raspbian check the config.ini file on bootup for wifi settings. This would allow users without EXT mounting abilities to pre-configure sd-cards to connect to their home wifi.

**Comment by XECDesign** [comment]
A recent update allows a wpa_supplicant.conf to be placed on the boot partition. This file is moved to /etc/wpa_supplicant on boot. This isn't in the image on the download page, but will be in the next one.
