### ISSUE TITLE
Package and distribute Vulkan driver for VideoCore IV (model 1 to 3+)

### ISSUE THREAD

**Issue by darkdragon-001** [RPi-Distro/repo#180]
It would be awesome to have [this newly released Vulkan driver for VideoCore IV](https://github.com/Yours3lf/rpi-vk-driver/releases/tag/v1.0) packaged and made available to all Raspbian users.

**Comment by XECDesign** [comment]
I'm sure once there's proper support in Mesa, that is deemed suitable for general use, it will be added to apt.
