### ISSUE TITLE
lirc package is not installable

### ISSUE THREAD

**Issue by nickrbogdanov** [RPi-Distro/repo#189]
See https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=235256

During the installation process, dpkg attempts to start the lirc service.  The service segfaults, leaving the package in a partially installed state.  The workaround from the linked thread is:

```
sudo cp /etc/lirc/lirc_options.conf.dist /etc/lirc/lirc_options.conf
sudo cp /etc/lirc/lircd.conf.dist /etc/lirc/lircd.conf
```

but this really ought to be fixed in the package itself.

**Comment by XECDesign** [comment]
Should be resolved
