### ISSUE TITLE
unar: symbol lookup error: unar: undefined symbol: main

### ISSUE THREAD

**Issue by imbalind** [RPi-Distro/repo#2]
I installed `unar` from `apt-get`, but when I run it I get the following error:

    unar: symbol lookup error: unar: undefined symbol: main

Even using `lsar` gives me the a similar error:

    lsar: symbol lookup error: lsar: undefined symbol: main

**Comment by XECDesign** [comment]
That package does not come from the raspberrypi.org repo.
Keep an eye on https://bugs.launchpad.net/raspbian/+bug/1165466 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746198
