### ISSUE TITLE
gpsd systemd does not start at boot

### ISSUE THREAD

**Issue by msemtd** [RPi-Distro/repo#20]
The gpsd package does not have the right systemd magic to start at boot despite having START_DAEMON="true" in /etc/default/gpsd

NB: I am not using USB hotplugging! Most of the raspbian gpsd workarounds for the startup problems seem to rely on udev rules.

Also the "-G" option is ignored by systemd as the socket access is restricted by /lib/systemd/system/gpsd.socket

**Comment by XECDesign** [comment]
From what I gather, the service is meant to start when there's a request on that socket.
https://lists.debian.org/debian-user/2015/10/msg01401.html

In any case, if this doesn't work as intended, the bug would belong to the package itself, which comes from raspbian.org and compiled from the debian package. So I think any bug reports which aren't pi specific should go here https://bugs.debian.org .
