### ISSUE TITLE
vlc: missing support for MMAL video output on Raspberry

### ISSUE THREAD

**Issue by arufl** [RPi-Distro/repo#201]
Upgrading to 3.0.11-0+deb9u1 on Stretch the video output module named "MMAL x11 splitter fro Raspberry Pi" disappeared.
Maybe  a ./configure switch is missing.

**Comment by XECDesign** [comment]
The current release of Raspberry Pi OS is Buster. Stretch is no longer getting updates from us, so Debian's security fixes take priority.
