### ISSUE TITLE
Package libx11-xcb-dev broken due to incorrect dependency version

### ISSUE THREAD

**Issue by benjamincburns** [RPi-Distro/repo#204]
When I try to install `libx11-xcb-dev` on the latest version of RPi OS, it fails due to unmet dependencies.

`libx11-xcb-dev : Depends: libx11-xcb1 (= 2:1.6.7-1) but 2:1.6.7-1+deb10u1 is to be installed`

I'm guessing that the `libx11-xcb-dev` package's metadata is incorrect.

**Comment by benjamincburns** [comment]
I'm guessing that this is a similar issue to #182

**Comment by XECDesign** [comment]
Not seeing any such issue on this end.

Did you run `sudo apt update` first? What's the output of `apt policy`?

**Comment by benjamincburns** [comment]
Yes, I ran `sudo apt update.` In the end I followed the workaround suggested in #182 (force installing it via `dpkg`), so I'm not sure if the outout of `apt policy` will be all that telling. I'm not near the device at the moment here, but I'll go ahead and report back with that as soon as I am.

**Comment by benjamincburns** [comment]
I wound up ditching this project and the rpi with it. Since I haven't seen a wealth of "me toos" on this issue, I'll go ahead and close it.
