### ISSUE TITLE
gnucash

### ISSUE THREAD

**Issue by AquaMCU** [RPi-Distro/repo#205]
gnucash has released version 4.2 of its software, the current repos has 3.4 in there. Can you please use the new version?

While you are on it, can you please add the support package for sqlite?

https://github.com/hoekit/GnuCash-SQLite

Thank you !

**Comment by XECDesign** [comment]
Sorry, wrong place. Those packages come from Raspian's repo, not ours. Raspbian tracks Debian, which is not a rolling release distro. For stability, packages are locked to the versions that were frozen at release and usually only security fixes are added.
