### ISSUE TITLE
DHCP Client Fails to update NTP servers

### ISSUE THREAD

**Issue by iandall** [RPi-Distro/repo#212]
By default RPI now uses systemd-timesyncd as an ntp client and dhcpcd5 fo the dhcp client. The former will use ntp servers advised by dhcp, but only on links managed by systemd.network using the built-in dhcp client. The net effect is that out of the box, ntp does not use the servers advertised by dhcp.

Alternative packages providing ntp are ntp, openntpd and chrony.  The dhcpd5 package provides /lib/dhcpcd/dhcpcd-hooks/50-ntp.conf, which purports (in the comments) to support all three (ntp, openntpd and chrony), but it fails to properly configure chrony. It doesn't look in the right place for chrony.conf and (if that is fixed) chronyd does not use the created runtime ntp.conf.

It does work with the ntp package (if you enable "option ntp_servers" in dhcpcd.conf). I haven't tested openntpd.

I think the dhcp advised ntp_servers should work out of the box or with minimal configuration. It would be nice if the light weight ntp clients were supported, or at least document that they are unsupported in this role.

**Comment by XECDesign** [comment]
dhcpcd NTP hooks in Bullseye come from Debian now and should work a bit better. Is this still an issue in Bullseye?
