### ISSUE TITLE
Packages libsoundio1, libsoundio-dev are missing from Raspian Buster

### ISSUE THREAD

**Issue by jcp-sd** [RPi-Distro/repo#215]
The packages libsoundio1, libsoundio-dev are missing from Raspian Buster?

This looks to be an oversight of some sort as the armhf pkgs _are available_ in vanilla Debian Buster for ARM;

https://packages.debian.org/search?keywords=libsoundio&searchon=names&suite=stable&section=all

They are in bullseye, so the packages are already in the Raspian pool here;

http://raspbian.raspberrypi.org/raspbian/pool/main/libs/libsoundio/

Was this perhaps a timing issue? (Package appeared in vanilla Buster after a snapshot of it was made for Raspian Buster).

I was able to build it from source OK and can't find any other issue that is blocking it...

**Comment by XECDesign** [comment]
Looks like it fails to build:

http://buildd.raspbian.org/status/package.php?p=libsoundio+&suite=buster-staging

This isn't one of our packages, so it should be reported here - https://bugs.launchpad.net/raspbian
