### ISSUE TITLE
Add `apt-get clean` option to pi-packages

### ISSUE THREAD

**Issue by dilyanpalauzov** [RPi-Distro/repo#222]
To be honest, I do not know where to report `pi-package(s)` matters.  On a Raspberry Pi I have disabled the apt-daily and apt-daily-upgrade services/timers.  I want to ship systems with SD cards, which just open a webpage on power on.  Once a year I want that my users manually update/upgrade the software using pi-package(s).  I do not want to run the daily update services, because they cause I/O to the SD card and can damage the card unnecessary soon.

For this the users have to do two steps over the Options menu:
* first update the packages lists;  
* then upgrade the software, based on the updated package lists; and
* (ideally) call `apt-get clean` to free space.

The first problem is, that pi-package has no equivalent for `apt-get clean`.  The second problem is, that this should really be in total one step.  Asking the users first to update the package list and then to upgrade the software, based on the updated packages lists, is error prone.  Some users will definitely do the things in the reverse order.

Please add a single action to pi-packages, which does all the steps in a row by requiring a single action from the user.

I propose adding a command-line option to pi-packages, which calls `apt-get clean` whenever pi-package is closed.

I propose adding a command line option to pi-packages, which calls `apt-get update` any time pi-packages is called with this option and then the (confusing) Options → “Update package list” option is hidden from the menu.

**Comment by XECDesign** [comment]
@spl237

**Comment by spl237** [comment]
I won't be doing anything to pi-package; it's just a third-party apt front-end which I tidied up a bit to make the UI less migraine-inducing. Finding a better alternative has been on the to-do list for a while - perhaps synaptic or something like that? If you don't like it, feel free to uninstall it, or not use it, but it's not worth putting any maintenance effort into; it's a very old piece of software at this stage.
