### ISSUE TITLE
v4l2loopback error

### ISSUE THREAD

**Issue by gam3t3chelectronicshobbyhouse** [RPi-Distro/repo#225]
Getting the following any help would be great.  This happened after current upgrades 
since it happened even attpempted firmware update. 
Currently also getting super laggy mouse and keyboard response on typing at time it locks up even 
Running a RPi 4 8gb with m.2 drive
no  issues until today. 

The following is from Terminal:
Error! Bad return status for module build on kernel: 5.4.83+ (aarch64)
Consult /var/lib/dkms/v4l2loopback/0.12.5/build/make.log for more information.
dpkg: error processing package v4l2loopback-dkms (--configure):
 installed v4l2loopback-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 v4l2loopback-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

The following is from the make.log
DKMS make.log for v4l2loopback-0.12.5 for kernel 5.4.83+ (aarch64)
Sat 30 Jan 2021 06:09:14 PM PST
Building v4l2-loopback driver...
make -C /lib/modules/5.4.83+/build M=/var/lib/dkms/v4l2loopback/0.12.5/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.83+'
  CC [M]  /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o] Error 1
make[1]: *** [Makefile:1732: /var/lib/dkms/v4l2loopback/0.12.5/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.83+'
make: *** [Makefile:43: v4l2loopback.ko] Error 2

-------More info----
Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux

/opt/vc/bin/vcgencmd version
Jan 27 2021 22:19:57 
Copyright (c) 2012 Broadcom
version 99d9a48302e4553cff3688692bb7e9ac760a03fa (clean) (release) (start)

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

-------Full error when doing any updates now-------

sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up v4l2loopback-dkms (0.12.5-1) ...
Removing old v4l2loopback-0.12.5 DKMS files...

Deleting module version: 0.12.5
completely from the DKMS tree.

Done.
Loading new v4l2loopback-0.12.5 DKMS files...
It is likely that 5.10.11-v8+ belongs to a chroot's host
Building for 5.10.1+, 5.10.11+, 5.10.11-v7+, 5.10.11-v7l+, 5.10.11-v8+, 5.10.1-v7+, 5.10.1-v7l+, 5.10.1-v8+, 5.4.42+, 5.4.42-v7+, 5.4.42-v7l+, 5.4.42-v8+, 5.4.45+, 5.4.45-v7+, 5.4.45-v7l+, 5.4.45-v8+, 5.4.61+, 5.4.61-v7+, 5.4.61-v7l+, 5.4.61-v8+, 5.4.65+, 5.4.65-v7+, 5.4.65-v7l+, 5.4.65-v8+, 5.4.81+, 5.4.81-v7+, 5.4.81-v7l+, 5.4.81-v8+, 5.4.83+, 5.4.83-v7+, 5.4.83-v7l+ and 5.4.83-v8+
Module build for kernel 5.10.1+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.11+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.11-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.11-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.11-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.1-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.1-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.10.1-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.42+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.42-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.42-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.42-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.45+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.45-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.45-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.45-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.61+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.61-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.61-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.61-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.65+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.65-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.65-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.65-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.81+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.81-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.81-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 5.4.81-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.4.83+
Error! Bad return status for module build on kernel: 5.4.83+ (aarch64)
Consult /var/lib/dkms/v4l2loopback/0.12.5/build/make.log for more information.
dpkg: error processing package v4l2loopback-dkms (--configure):
 installed v4l2loopback-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 v4l2loopback-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by XECDesign** [comment]
Am I correct in assuming you're running the 64bit kernel in a 32bit userland?

If so, there's currently no armhf->aarch64 crosscompiler for dkms to use, so it's not going to work. I believe it works as expected when running a full 64bit image.
