### ISSUE TITLE
Buster missing libasound.so?

### ISSUE THREAD

**Issue by shokuntsuki** [RPi-Distro/repo#226]
I have pyalsaaudio and libasound2-dev installed.  The code I am attempting to use has worked with previous installations of Raspbian.

As best I can tell, pyalsaaudio relies on /usr/lib/libasound.so being installed.  libasound.so is present in Debian's distribution but not in Buster.  Is there a reason for leaving it out of Buster?  (see https://larsimmisch.github.io/pyalsaaudio/pyalsaaudio.html#alsa-and-python)

**Comment by XECDesign** [comment]
Everything looks okay from this end.

```
$ dpkg -S /usr/lib/arm-linux-gnueabihf/libasound.so
libasound2-dev:armhf: /usr/lib/arm-linux-gnueabihf/libasound.so
```

Which matches the paths in Debian:
```
/usr/lib/arm-linux-gnueabihf/libasound.so | libasound2-dev [armhf]
```
https://packages.debian.org/search?suite=buster&arch=any&mode=exactfilename&searchon=contents&keywords=libasound.so

**Comment by shokuntsuki** [comment]
This did not turn out to be my problem, thank you!
