### ISSUE TITLE
Error in zfs-dkms with 5.10.11 kernel

### ISSUE THREAD

**Issue by bcarrella** [RPi-Distro/repo#227]
**After apt-get update & apt-get upgrade** on RaspberryPi 4

run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.10.11+ /boot/kernel.img
run-parts: executing /etc/kernel/postinst.d/dkms 5.10.11+ /boot/kernel.img
/etc/kernel/postinst.d/dkms:
Error! Bad return status for module build on kernel: 5.10.11+ (armv7l)
Consult /var/lib/dkms/zfs/0.8.6/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.10.11+ /boot/kernel.img
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.10.11-v7+ /boot/kernel7.img
run-parts: executing /etc/kernel/postinst.d/dkms 5.10.11-v7+ /boot/kernel7.img
/etc/kernel/postinst.d/dkms:
Error! Bad return status for module build on kernel: 5.10.11-v7+ (armv7l)
Consult /var/lib/dkms/zfs/0.8.6/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.10.11-v7+ /boot/kernel7.img
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.10.11-v7l+ /boot/kernel7l.img
run-parts: executing /etc/kernel/postinst.d/dkms 5.10.11-v7l+ /boot/kernel7l.img
/etc/kernel/postinst.d/dkms:
Error! Bad return status for module build on kernel: 5.10.11-v7l+ (armv7l)
Consult /var/lib/dkms/zfs/0.8.6/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.10.11-v7l+ /boot/kernel7l.img
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.10.11-v8+ /boot/kernel8.img
run-parts: executing /etc/kernel/postinst.d/dkms 5.10.11-v8+ /boot/kernel8.img
/etc/kernel/postinst.d/dkms:
Error! echo
Your kernel headers for kernel 5.10.11-v8+ cannot be found at
/lib/modules/5.10.11-v8+/build or /lib/modules/5.10.11-v8+/source.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.10.11-v8+ /boot/kernel8.img

[make.log](https://github.com/RPi-Distro/repo/files/5935897/make.log)

**Comment by bcarrella** [comment]
Same error was reported to Debian package maintainers:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979158

**Comment by XECDesign** [comment]
I don't think they're on 5.10, so they won't be able to help. We'd need to update the zfs package on our end.

**Comment by bcarrella** [comment]
Thank you @XECDesign 
I can't access my external zfs usb drive at the moment. When the update will be available on apt repo?

**Comment by XECDesign** [comment]
I've just added an updated version which should show up publicly within an hour.

**Comment by bcarrella** [comment]
Problem is not resolved.
Maybe a kernel downgrade back to 5.4.x can solve the issue?

[make.log](https://github.com/RPi-Distro/repo/files/5967411/make.log)

Meta:          1
Name:          zfs
Branch:        1.0
Version:       0.8.6
Release:      1~bpo10+1
Release-Tags:  relext
License:       CDDL
Author:        OpenZFS on Linux
**Linux-Maximum: 5.9**
Linux-Minimum: 2.6.32

**Comment by XECDesign** [comment]
Not sure why you have 0.8.6. The updated version is 2.0.2.

**Comment by bcarrella** [comment]
OK problem resolved purging and reinstalling zfs packages.
Now all zfs packages versions are 2.0.2
Thank you very much.

**Comment by XECDesign** [comment]
Thanks for confirming everything is okay now. Not sure what went wrong, but I'll keep an eye on further reports of people having trouble upgrading.
