### ISSUE TITLE
Upgrade messed with my trust settings in apt

### ISSUE THREAD

**Issue by jgoerzen** [RPi-Distro/repo#230]
Hi,

After today's dist-upgrade, I found this file:

/etc/apt/trusted.gpg.d/microsoft.gpg

It is important to me that only sources that are authorized be used for package installation.  Treating other sources as trusted should not happen with a dist-upgrade point release.

This appears to be related to sources.list.d/vscode.list which is also of concern but the primary concern is that the trust model of a running system is altered without my permission.

**Comment by XECDesign** [comment]
You can find a more official response here:

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=302591&p=1813830#p1813830

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=302591&p=1815834#p1815834
