### ISSUE TITLE
raspbian-nspawn-64 transparently turns on no-password sudo

### ISSUE THREAD

**Issue by aripollak** [RPi-Distro/repo#234]
The raspbian-nspawn-64 package installs a `/etc/sudoers.d/010_sudo-nopasswd` file that turns on no-password sudo for anyone in the sudo group. This is a really bad/surprising thing to be doing, and it doesn't seem necessary. Can it be removed?

I'd send this upstream, but the upstream repo appears to be unmaintained.

**Comment by XECDesign** [comment]
I think the thing to do may be to remove the package from the repo, since it has been deprecated for a while.

**Comment by XECDesign** [comment]
Package is no longer present in Bullseye.
