### ISSUE TITLE
Error! The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which...

### ISSUE THREAD

**Issue by pheiduck** [RPi-Distro/repo#236]
Background:

Use wireguard installed with this script https://github.com/Nyr/wireguard-install

Wireguard is working anyway

Get this from todays Kernel Update updated via apt / stable buster repo > 1.20210303-1
```
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v7+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v7l+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.10.17-v8+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
```

**Comment by pheiduck** [comment]
https://github.com/raspberrypi/firmware/issues/1545

**Comment by XECDesign** [comment]
That script doesn't seem to support Raspberry Pi OS. AFAIK, Wireguard is already provided as a kernel module and you can just run `sudo apt install wireguard-tools` to get the tools

**Comment by XECDesign** [comment]
Taking a closer look, it seems like that message comes from the `wireguard-dkms` package, which you should be able to remove.

**Comment by pheiduck** [comment]
hm, sure that wireguard won't work if I do this?
Maybe it resolved by an update of `wireguard-dkms`?

pkg diffs buster vs sid
https://packages.debian.org/buster-backports/wireguard-dkms
https://packages.debian.org/sid/wireguard-dkms

**Comment by XECDesign** [comment]
> hm, sure that wireguard won't work if I do this?

Why do you believe that?

**Comment by pheiduck** [comment]
Update: uninstalled wireguard-dkms dkms
Works anyway
