### ISSUE TITLE
ALSA IPC missconfiguration

### ISSUE THREAD

**Issue by DarioDaF** [RPi-Distro/repo#240]
I installed on my RPi3B+ (and a RPi3B for testing later) the version 2021-01-11 of raspios, and configured an external card to work with chromium (using ALSA_CARD=DevName).

Today I realize it doesn't work on RPi3B and tried to set up the system back on the RPi3B+ without any success, both with previous and new kernel, it seems to be a ALSA/chromium bug or a repo that got updated into the main without testing.

Current setup uses RPIOS lite and tried both `alsa-utils/testing,now 1.1.8-2+rpt1 armhf` and `alsa-utils/stable 1.1.8-2 armhf alsa` modules and `chromium/stable 88.0.4324.146-1~deb10u1 armhf` which are the only available repos up.

I have no way to downgrade apparently because no other version are available, the error says:
```
ALSA lib pcm_dsnoop.c:602:(snd_pcm_dsnoop_open) unable to create IPC semaphore
[17793:17793:0406/125741.675342:ERROR:alsa_util.cc(204)] PcmOpen: default,Operation not permitted
```

And apparently not even bypassing dmix (that seemed to be sometime the cause of this type of error in other distros) or configuring IPC permission in alsa.conf resolved the issue making RPIOS impossible to be used for my application (needing a mic input).

I'll try to use Ubuntu Server as os and repo to check if the problem is the same, a default install without changing configuration in my opinion should not be broken so any config related possible issues is better if they got fixed upstream, I am anyway available if needs testing.

Card for full spec (I tested it on 3 audio cards all with cmedia chipset as racomended on the wikis)
```
# aplay -l
card 2: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

# lsmod
snd_pcm                94208  2 snd_usb_audio,snd_bcm2835
snd_timer              32768  1 snd_pcm

# lsusb
Bus 001 Device 006: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)

# aplay -L (contains also some insight on alsa.config which is default from repo)
default:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
sysdefault:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Hardware device with all software conversions
```

**Comment by XECDesign** [comment]
Is this still an issue in Bullseye?
