### ISSUE TITLE
raspbian 10 fetch packages error in thailand mirror

### ISSUE THREAD

**Issue by xeleniumz** [RPi-Distro/repo#241]
Hello community , I found 404 http error from trying to download package from 
http://mirror1.ku.ac.th/raspbian/raspbian/
I'm not sure that many packages can not down or update. but in my case main package with cmake , python and main lib* is not work , now I fixed it by change repository to Singapore location with this url http://mirror.nus.edu.sg/raspbian/raspbian
thank you.

![Screenshot 2021-04-07 182524](https://user-images.githubusercontent.com/9983597/113860562-5d586d00-97d0-11eb-90a3-5896697b89a3.png)

**Comment by XECDesign** [comment]
Hello,

This repo is for issues with archive.raspberrypi.org, not raspbian. Raspbian's bug tracker can be found here: https://bugs.launchpad.net/raspbian
