### ISSUE TITLE
raspberrypi-artwork package has no copyright file

### ISSUE THREAD

**Issue by iluminat23** [RPi-Distro/repo#247]
The package has no copyright file. I created a ticket at the repo where the package originated: https://github.com/asb/raspberrypi-artwork/issues/1. @asb that the repo might be transferred to https://github.com/RPi-Distro. He mentioned that the Raspberry Pi legal needs to decide the license hence the trademarked Raspberry Pi logo.

**Comment by XECDesign** [comment]
I don't think there are any plans to build newer versions of this package since I don't think it will be added to bullseye.

**Comment by iluminat23** [comment]
OK, thank you.
