### ISSUE TITLE
Missing github repos

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/repo#25]
I'm not sure if this is the best place to report this issue, but I dunno if there's somewhere more suitable.

During a recent `sudo apt-get dist-upgrade` I noticed there was a new `pishutdown` package, so I did `apt-cache show pishutdown` and it says `Homepage: http://github.com/raspberrypi/pishutdown`, but that URL just 404s.

Also, I noticed that `cat /boot/issue.txt` says `Generated using Pi-gen, https://github.com/RPi-Distro/Pi-gen, stage4` and that repo is missing too. (I assume this latter project is an updated fork of https://github.com/RPi-Distro/spindle ?)

**Comment by XECDesign** [comment]
pishutdown is there, just private for now. The source itself should be in apt.

Pi-gen hasn't been published yet.

**Comment by spl237** [comment]
Source code repos will generally be kept private until the relevant apps have been released. I'm not sure why people would want the source of something they don't even know exists yet...

Patience, as they say, is a virtue. :)

**Comment by XECDesign** [comment]
@spl237 pishutdown is in apt already.

**Comment by spl237** [comment]
In that case, I'll open up the repo when I'm next in the office...

**Comment by lurch** [comment]
@XECDesign Any idea if / when Pi-gen will get published? I can imagine people would find it quite useful for e.g. creating customised Raspbian-Lite images?

**Comment by ZanderBrown** [comment]
@lurch it would be so useful particularly if a nice interface was available for it so you could have your SD card already to go as a webserver or whatever before you've even plugged your pi in.

**Comment by lurch** [comment]
@ZanderBrown I have no insider info, but I'm expecting it'll be a purely script-based application, with the only "user interface" being a configuration text-file you'll need to edit.

**Comment by ZanderBrown** [comment]
My point was more that once it was available a wizard for generating said file could be made
