### ISSUE TITLE
The debian/copyright file is missing in package rpi-update

### ISSUE THREAD

**Issue by zhan-kunbus** [RPi-Distro/repo#250]
According to the Debian Policy Manual, the Copyright info is needed, which can be put in file debian/copyright.

However, should a repository be created in RPi-Distro and put the debian files in it ?

**Comment by zhan-kunbus** [comment]
Can the firmware, kernel & modules be well managed/updated by the apt package management **without** the rpi-update ?
It looks to me that, most of the files are contained in the package raspberrypi-bootloader, by which most files updated by rpi-update are managed.
https://github.com/Hexxeh/rpi-update/blob/master/README.md#notes

**Comment by XECDesign** [comment]
Yes, rpi-update came along before there was an apt package. It has the advantage of being able to get the latest version before it goes to the `stable` branch and lets you switch between different versions, but in general it's not necessary for the average user.

I will add the copyright, but this isn't a package that we're trying to get into Debian, so adhering to Debian's policies is not particularly important.

**Comment by XECDesign** [comment]
Should be sorted
