### ISSUE TITLE
Update nftables package to newer version

### ISSUE THREAD

**Issue by wirefalls** [RPi-Distro/repo#255]
Would it be possible to update the nftables package to a newer version? The package in the repo is v0.9.0-2, which is quite old. The current version from the netfilter project is v0.9.9. Newer versions have many fixes that would help to ease the transition to nftables. Thank you very much.

**Comment by XECDesign** [comment]
Added 0.9.6 from Debian backports.

**Comment by wirefalls** [comment]
I tested v0.9.6 from the repo and everything works great. Thank you @XECDesign

**Comment by XECDesign** [comment]
No worries. Thanks for testing.
