### ISSUE TITLE
postgresql-13 - ORC error: No callback manager available for armv6k-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by joergsch** [RPi-Distro/repo#259]
Since upgrading to postgresql-13 the log is filled with lines showing:
ORC error: No callback manager available for armv6k-unknown-linux-gnueabihf
I don't see these lines on my other Linux system (AMD64).
Adding
jit = off
to /etc/postgresql/13/main/postgresql.conf stops these messages.

**Comment by XECDesign** [comment]
Since that's not a package from our repo, it should be reported here:

https://bugs.launchpad.net/raspbian
