### ISSUE TITLE
The firmware-realtek package is outdated and missing drivers.

### ISSUE THREAD

**Issue by marinmo** [RPi-Distro/repo#261]
Relevant dmesg:

root@rpi ~> dmesg | grep r8152
[    1.355551] usbcore: registered new interface driver r8152
[    2.103869] r8152 2-2:1.0: Direct firmware load for rtl_nic/rtl8153a-3.fw failed with error -2
[    2.103922] r8152 2-2:1.0: unable to load firmware patch rtl_nic/rtl8153a-3.fw (-2)
[    2.145538] r8152 2-2:1.0 eth1: v1.12.11
[    5.361309] r8152 2-2:1.0 enxd03745cfcc8f: renamed from eth1
[   15.961070] r8152 2-2:1.0 enxd03745cfcc8f: carrier on

root@rpi ~> lsusb
Bus 002 Device 002: ID 2357:0601 TP-Link
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

root@rpi ~> apt info firmware-realtek
Package: firmware-realtek
Version: 1:20190114-2+rpt1

Kernel tree log: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/rtl_nic

Fixed in Ubuntu as per this bug: https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/1890641

It doesn't seem they're built into the kernel or as modules, so we have to rely on this package for the drivers. Could this package get updated to match the kernel tree? Do note that it'd mean the driver would be rtl_nic/rtl8153a-4.fw.

Thanks in advance!

**Comment by XECDesign** [comment]
Unfortunately not. Debian's packages are going to be out of date sometimes since they lock their upstream package versions in before release. I believe bullseye will have the necessary files, so the problem will resolve itself once we release the image.
