### ISSUE TITLE
[Bullseye+Buster] missing 'mage' package crashes X session

### ISSUE THREAD

**Issue by jbarth-ubhd** [RPi-Distro/repo#269]
... when configured.

*mage* is the virtual magnifying glass, configurable in the task bar.

After installing *mage* with `apt install mage` everything works fine.

Package is not by default in *Bullseye*, even in *Raspberry Pi OS with desktop and recommended software*

**Comment by XECDesign** [comment]
@spl237

**Comment by spl237** [comment]
mage should not be installed by default. It should only be installed when required; adding the Magnifier using Recommended Software installs it. The lack of it does not crash the X session on any bullseye image I have used in several months of testing.

What are you actually doing when the X session crashes?

**Comment by jbarth-ubhd** [comment]
When trying to configure the "not installed" magnifier (right mouse button on taskbar), X session crashes.

**Comment by spl237** [comment]
Do you mean if you right-click the taskbar, open Panel Preferences, go into Panel Applets, select the Magnifier and then click the Preferences button?

I can indeed crash the X session like that - which I will look into fixing - but I can't find any other way of causing a crash, and that sequence is pretty unlikely to happen very often!

**Comment by spl237** [comment]
Fixed crash when that button is pressed - if you find any other way of causing the crash, please re-open the issue.

Many thanks!
