### ISSUE TITLE
Bullseye - libcamera-still -o - sends the output to a file name - and not to stdout

### ISSUE THREAD

**Issue by knutegit** [RPi-Distro/repo#271]
Pi4 2GB Current 32bit Bullseye.  libcamera-still -o - sends the output to a file name - and not to stdout.

**Comment by ghollingworth** [comment]
Needs to be in https://github.com/raspberrypi/libcamera-apps

**Comment by knutegit** [comment]
> Needs to be in https://github.com/raspberrypi/libcamera-apps

Thanks, don't know my way around here.  It's in libcamera-apps now.
