### ISSUE TITLE
[Bullseye] matchbox-keyboard segmentation fault

### ISSUE THREAD

**Issue by Nathoufresh** [RPi-Distro/repo#273]
Launching matchbox-keyboard without additional arg works fine but when I try to choose a layout like
$ matchbox-keyboard keyboard
I get a segmentation fault.

**Comment by XECDesign** [comment]
Does it still segfault in Bullseye?

**Comment by vipierozan99** [comment]
have this issue as well

OS: Debian GNU/Linux 12 (bookworm) aarch64 
Host: Raspberry Pi 4 Model B Rev 1.5
