### ISSUE TITLE
Puppet not working on Bullseye

### ISSUE THREAD

**Issue by Jmkgabriel** [RPi-Distro/repo#277]
I hope this is the correct place to report this bug, I apologize if it isn't.

On armv71 architecture, puppet fails to execute with the error of "Failed with result 'signal'".  There isn't much more in regards to information via logging.  

Found a similar bug report on debians mail list, [https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1815284.html](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1815284.html).
I followed advice from one of the posters in that thread, and was able to get puppet to work by manually downloading and installing package from the debian repos, in my case:  [http://ftp.debian.org/debian/pool/main/f/facter/libfacter3.14.12_3.14.12-1+b2_armhf.deb](http://ftp.debian.org/debian/pool/main/f/facter/libfacter3.14.12_3.14.12-1+b2_armhf.deb).  The raspberry pi repo installs libfacter3.14.12_3.14.12-1+b1_armhf.deb.  Once this is done, puppet will run as expected.  

Steps to reproduce:
Install raspberry pi's bullseye lite image
Install puppet and try to start it

If there is any further info needed, i can provide.

**Comment by XECDesign** [comment]
It probably belongs here: https://bugs.launchpad.net/raspbian

**Comment by Jmkgabriel** [comment]
Posting it there, thank you for the response.
