### ISSUE TITLE
Bullseye Telegram Desktop

### ISSUE THREAD

**Issue by g1gsw** [RPi-Distro/repo#284]
Telegram Desktop in Bullseye is out of date and it is not allowed to be used any longer, if you try and connect it says it cannot as use of the version in Bullseye is no longer allowed as it is out of date.

**Comment by XECDesign** [comment]
We don't build, maintain or host telegram packages. The issue should be reported to Debian (https://bugs.debian.org/).

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001016

It seems like they suggest the package should be removed altogether, so the solution may be to use the snap, flatpak or your own build.
