### ISSUE TITLE
Keyboard repeat rate cannot be set

### ISSUE THREAD

**Issue by lucatrv** [RPi-Distro/repo#289]
See issue description and solution [here](https://raspberrypi.stackexchange.com/questions/99913/permanently-set-keyboard-repeat-rate-on-raspberry-pi).

Apparently `~/.config/autostart/LXinput-setup.desktop` is started too early, a small delay fixes the issue.

**Comment by XECDesign** [comment]
@spl237

**Comment by spl237** [comment]
Lxinput-setup.desktop is not the issue; the issue is that mutter overwrites those settings anyway. lxinput was modified last week to make the appropriate settings for mutter, so this should already be fixed - a sudo apt update / sudo apt full-upgrade will get the fix.
