### ISSUE TITLE
libraspberrypi-bin package is not included in the Raspbian image for x*

### ISSUE THREAD

**Issue by crokett** [RPi-Distro/repo#308]
When I downloaded and installed the ISO image to install Raspbian on a desktop PC from here:

https://www.raspberrypi.com/software/raspberry-pi-desktop/

I wanted to install some of the utilities in the libraspberrypi-bin package.  However, this package is not included in that distribution.

**Comment by crokett** [comment]
This is the listing of the packages for Raspbian on AMD64. http://[archive.raspberrypi.org/debian/dists/buster/main/binary-amd64/Packages](http://archive.raspberrypi.org/debian/dists/buster/main/binary-amd64/Packages)

It has one package that refers to libraspberrypi-bin, but doesn't have the actual libraspberrypi-bin.    I am looking for that package built for AMD64 or x86_64

**Comment by XECDesign** [comment]
Those are generally only useful when running on an actual pi. Is there a specific tool you're after?

**Comment by crokett** [comment]
> Those are generally only useful when running on an actual pi. Is there a specific tool you're after?

Yes.  I was looking for vcgencmd, but I figured out that it won't run on other boards. I will close this issue.
