### ISSUE TITLE
broken rpi-eeprom package

### ISSUE THREAD

**Issue by bittin** [RPi-Distro/repo#311]
Hey!

Todays update of rpi-eeeprom is using wierd compression and is broken

https://pastebin.com/3jin4Cea

**Comment by XECDesign** [comment]
Thanks for raising the issue. It should be fixed now.

Looks like Ubuntu's default compression algorithm has changed to one that's not supported by default in Bullseye.

**Comment by bittin** [comment]
Yep, its fixed now, had the same problem in Debian Unstable, but now its fixed so closing
