### ISSUE TITLE
snmpd fail to install - missing libmariadb3

### ISSUE THREAD

**Issue by awneil** [RPi-Distro/repo#314]
Trying to set up a "local" repository, following these:

https://www.youtube.com/watch?v=vUKOAqVxVNM - Create A Raspberry Pi APT Local Offline Repository

https://www.centlinux.com/2021/04/create-local-apt-repository-in-ubuntu.html - How to Create Local APT Repository

I take the packages from an RPi where `snmpd` is installed and working

But, when trying to install `snmpd` from that repository, it fails - saying it can't find libmariadb3:

```
~ $ sudo apt install snmpd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 snmpd : Depends: libmariadb3 (>= 3.0.0) but it is not installable
         Depends: libsnmp30 (= 5.7.3+dfsg-5+deb10u2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

looking in the repository folders, I don't see any packages with any names like "libmariadb3"

It won't install manually:
```
~ $ sudo apt-get install  libmariadb3
[sudo] password for pi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libmariadb3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmariadb3' has no installation candidate
```

I tried `apt show`:
```
~ $ apt show libmariadb3
Package: libmariadb3
State: not a real package (virtual)
N: Can't select candidate version from package libmariadb3 as it has no candidate
N: Can't select versions from package 'libmariadb3' as it is purely virtual
N: No packages found
```

So how do I get this installed?

**Comment by awneil** [comment]
#216 was resolved by setting the date correctly - but that is already done in my system.

**Comment by XECDesign** [comment]
Can't vouch for the quality of random blogs and youtube channels, but snmpd itself installs on this end.

For general support, I'd recommend [the forum](https://forums.raspberrypi.com/).

**Comment by awneil** [comment]
> Can't vouch for the quality of random blogs and youtube channels

Indeed. Can you point to any reliable sources for setting up a local (offline) repository?

> snmpd itself installs on this end.

Yes, it does when online - but not from the local (offline) repository

> For general support, I'd recommend [the forum](https://forums.raspberrypi.com/).

OK:  https://forums.raspberrypi.com/viewtopic.php?t=342464
