### ISSUE TITLE
Mount.cifs kernel issue

### ISSUE THREAD

**Issue by Tiemichael** [RPi-Distro/repo#315]
Background:
I am using the most recent Raspberry Pi OS (64bit)  (uname -a : Linux Raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux) on a Raspberry 4B. 
When trying to mount an old Mediaserver (AcRyan:PlayOn) via the (only available) CIFS-protocol I fail, although mounting from Windows 10, Ubuntu 16.04, 18.04 and 20.04 works fine. (other newer devices mount without any problems).
After intensive search I found '[Bug 215375](https://bugzilla.kernel.org/show_bug.cgi?id=215375) - Unable to mount cifs 1.0 shares'   as the most likely culprit for my issue.

Questions:
What is best way for me to overcome this issue?
I read that downgrading the kernel is a possibility (downgrade kernel from 5.15.76 to 5.14.x or lower) - but where can I find the kernel?
Is there an easy way to patch the kernel (as mentioned in the link above) ? 

Thanks for your help!

**Comment by XECDesign** [comment]
@popcornmix Thoughts?

I'm guessing since it's an upstream issue, we wait and see if upstream want to resolve it or if they're okay with breaking it.

**Comment by popcornmix** [comment]
From reading the linked thread I think the commit required is `cifs: fix regression in very old smb1 mounts`
That has been backported to v5.15.78, so just a bit newer than OP's kernel version.

@Tiemichael if you try using rpi-update kernel you should get a 5.15.84 kernel which includes the cifs regression fix.
Can you test that and report back?

Note: backups are advised when using rpi-update (although currently rpi-update kernel is pretty close to stable).

**Comment by Tiemichael** [comment]
Where can I find the V5.15.78 kernel or the 'Git hash' required for rpi-update? 
I am not familiar with the numbering etc.

Thanks

**Comment by popcornmix** [comment]
The rpi-update tool (installed by default on RPiOS) allows test firmware/kernel to be installed.
See: https://github.com/raspberrypi/rpi-update

**Comment by Tiemichael** [comment]
Where can I find  the mentioned 'Git hash' required for rpi-update?

**Comment by popcornmix** [comment]
git hash is optional. Without a hash you get the latest (which is what you want).

**Comment by Tiemichael** [comment]
I successfully upgraded the kernel to V5.15.84-v8+, and I am able to mount the MediaServer!

Thank you for the quick help!

**Comment by popcornmix** [comment]
Thanks for confirming. There will be a stable (i.e. from apt) kernel update soon after new year, which will include this fix, so you should be fine.
The apt upgrade will replace your rpi-update kernel, so nothing special should be needed from you when updated software.

**Comment by Tiemichael** [comment]
Thanks for the info!
