### ISSUE TITLE
Enable CONFIG_IP_SET_HASH_MAC as a module

### ISSUE THREAD

**Issue by moham96** [RPi-Distro/repo#316]
Please enable CONFIG_IP_SET_HASH_MAC as a module in the kernel

**Comment by alsldlflglhljlk** [comment]
What good will that do? If you need that specific feature, you can compile the kernel yourself.

**Comment by popcornmix** [comment]
These requests should be submitted to https://github.com/raspberrypi/linux/issues

But, as @alsldlflglhljlk says, you'll need to explain what use cases require this.
