### ISSUE TITLE
Build and add bcusdk and pthsem packages to repository

### ISSUE THREAD

**Issue by jobermayr** [RPi-Distro/repo#32]
http://www.meintechblog.de/2014/06/knx-eib-gateway-in-fhem-einbinden/

IMHO packages should be available on main repository since FHEM repository doesn't differentiate between Debian/Raspbian releases ...

**Comment by XECDesign** [comment]
As far as I can tell, that's written in Perl and is not platform specific. It should be safe to just install using the instructions they provide.

The best thing to do is get them into the standard debian repos and then it will flow into raspbian.
