### ISSUE TITLE
Can't log-in to Desktop remotely

### ISSUE THREAD

**Issue by easy-and-simple** [RPi-Distro/repo#329]
It is not possible to log-in to desktop via realvnc if wayland is enabled, because login prompt can't be removed, and if login promt appear desktop can't be entered via realvnc no matter with or without wayland.
So from there we have 2 issues:
1. Can't log-in to desktop via vnc if user is not already logged-in. If user is auto logged-in and log-out it can't log-in again via realvnc connection
2. If wayland is enabled, desktop auto log-in doesn't work and as a result desktop can't be accessed via realvnc

Next issue is with RDP
User root and default user can't log-in via RDP. If new user is created it can log-in but can't do anything because there are no groups assigned to it. Because sudo group is most important I assign at first sudo group and it can log-in and perform sudo command but user is limited and for example can't see camera window. If I add some other group to the new user in addition to sudo user can't log-in via RDP

Chrome browser have super lag if user is logged-in via realvnc and is completely useless. In same conditions firefox is responsive. There is no such issue if user is logged via RDP

**Comment by XECDesign** [comment]
Wayland is only an experimental feature in bullseye and we don't offer any support for it.

RealVNC does not support Wayland at all, so I don't expect that to ever work.

As far as RDP goes, again, it's not an option we support directly. If you have fixes for issues, we can add them.

@spl237
