### ISSUE TITLE
HPLIP plugin for ARM

### ISSUE THREAD

**Issue by drdanz** [RPi-Distro/repo#33]
According to [HPLIP release notess](http://hplipopensource.com/hplip-web/release_notes.html), the HPLIP plugin for the arm architecture is available since 3.15.4. At the moment on raspbian only version 3.14.6 is available, and therefore some HP printers are not supported.
On debian jessie-backports repository 3.16.3 is available and I can confirm that rebuilding that it works if rebuilt on a raspberry pi.

**Comment by XECDesign** [comment]
Sorry, didn't notice it was in backports. Will add it to the repo.

**Comment by drdanz** [comment]
Thanks!
