### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by ghost** [RPi-Distro/repo#334]
![install](https://github.com/RPi-Distro/repo/assets/142316563/1b204cb3-63c7-46f4-93d5-2db1e3870d94)

This setup should give me a Norwegian keyboard layout, I would think? But it does not, it gives me a US layout. No matter if the US keyboard box is ticked or not, it will always give me a US keyboard. Even when the English language box is not ticked, it will give me a US layout.

Also, the Norwegian letter å is shown as a code, in Bokmål. If the Norwegian letter å cannot be shown, then it is standard to use a double aa, like Bokmaal. That would be more correct and look a lot better than what is shown on the screen

**Comment by ghost** [comment]
Also posted here: https://github.com/raspberrypi-ui/piwiz/issues/30

**Comment by XECDesign** [comment]
Closing, since it was addressed there.
