### ISSUE TITLE
how to patch raspios's libdpkg-perl?

### ISSUE THREAD

**Issue by CarlFK** [RPi-Distro/repo#342]
I have a fix for libdpkg-perl that will fix a problem with the way the linux-version command fails to work with the way RaspiOS currently (as of Aug 28 beta bookworm) packages the kernel, which is influenced by the filename "kernel.img" being stored in the closed source start.elf.  "We will entirely rework the way we package the kernel ..." hasn't happened yet.

In the event the rework (or lack of) doesn't fix this bug, I'd like to get a patch submitted so that this bug is fixed regardless.

Also I can test the things that the patch fixes: building an initrd for all the installed kernels, which is why installing overlayroot doesn't work right.   It currently does not even build the current kernel because according to 'linux-version list' there is no current kernel.

So, the point of this post:
Where do I submit a PR to patch the raspios version of libdpkg-perl?

the fix:
https://github.com/CarlFK/pici/blob/main/ansible/roles/onpi/files/DebianLinux.pm#L88-L101

The bugs it fixes:
https://github.com/raspberrypi/bookworm-feedback/issues/21 overlayroot package does work
because:
https://github.com/RPi-Distro/repo/issues/320 linux-version list - does not list anything

**Comment by XECDesign** [comment]
> "We will entirely rework the way we package the kernel ..." hasn't happened yet.

It has (internally). And overlayroot, dkms and everything else 'just works'. At some point in the near future, the beta testers will get those images as well.
