### ISSUE TITLE
Kodi out of date and broken in testing

### ISSUE THREAD

**Issue by PanderMusubi** [RPi-Distro/repo#35]
Not sure where to report this. Was reported here https://bugs.launchpad.net/raspbian/+bug/1571196 but is not followed up. Since kodi is in the rasberry repo for Raspbian, not the raspbian repo for Raspbian, I thought perhaps it belows here

**Comment by rejhgadellaa** [comment]
+1

**Comment by PanderMusubi** [comment]
See launchpad for workaround.

**Comment by XECDesign** [comment]
We don't have 'testing' in raspberrypi.org. However, we should update our kodi packages soon.

**Comment by PanderMusubi** [comment]
this one is testing:

    deb [arch=armhf] http://mirrordirector.raspbian.org/raspbian/ testing main contrib non-free rpi

**Comment by diederikdehaas** [comment]
raspbian.org != raspberrypi.org

**Comment by PanderMusubi** [comment]
Thanks. So, bug reports for that go only to https://launchpad.net/raspbian ?

**Comment by diederikdehaas** [comment]
Bug reports for packages coming from raspbian.org, yes.
The statement you made in your first post in this issue is (completely) correct.
