### ISSUE TITLE
libraspberrypi-bin documentation outdated

### ISSUE THREAD

**Issue by Al-** [RPi-Distro/repo#351]
Hi
The debian package libraspberrypi-bin on bookworm (Version: 1:2+git20231018~131943+3c97f76-1) states 
```
$ dpkg --status libraspberrypi-bin
...
Source: raspberrypi-userland
...
Homepage: https://github.com/raspberrypi/userland
```
However, https://github.com/raspberrypi/userland/blob/master/README.md says that "this repo is ancient and deprecated".  The correct source and homepage is **https://github.com/raspberrypi/utils**

**Comment by XECDesign** [comment]
That package is in fact built from the userland repo. It's in the process of being replaced by raspi-utils.
