### ISSUE TITLE
apt update hangs on 512MB models running desktop

### ISSUE THREAD

**Issue by trejan** [RPi-Distro/repo#353]
There have been a few people complaining that apt update fails on Pi Zero 2 running desktop edition. The symptom is that it hangs during the reading changelogs step. The cause appears to be insufficient RAM as increasing CONF_SWAPSIZE in /etc/dphys-swapfile from 100 to 512 fixes it.

Running desktop on a 512MB model isn't optimal but updates should still work even if its slow. 64-bit Bookworm Lite does update without any problems but that has much more free RAM without the GUI running.

The dphys-swapfile package is already modified by Raspberry Pi to set 100MB so maybe time to increase the default?

**Comment by XECDesign** [comment]
This seems to be happening because bookworm's version of dpkg has introduced multi-threaded decompression for xz by default. On the original, it would work fine, but then on a zero 2, using additional cores makes it eat more RAM.

The next image will have a version of sys-mods which limits dpkg to a single thread if the device does not have enough RAM. Don't know enough to say whether we should also increase swap.

**Comment by Murray2015** [comment]
Hello! Dropping in to say a [few people on this thread](https://forums.raspberrypi.com/viewtopic.php?p=2224570&hilit=zero+2#p2224570) (inc. myself) are still finding this issue in the prod image. However, I don't have enough experience to be able to offer any help; sorry! 🙂

**Comment by XECDesign** [comment]
Thanks for the heads up. Looks like the dpkg fix wasn't enough in some cases and bumping swap is necessary.

I'll try defaulting to 200 instead and monitor if that's enough.

https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/1f88fa7abe59d878920cd02582a5f1c1ec69f531
https://github.com/RPi-Distro/pi-gen/commit/75fe47c7571c533ad52c43e03b440b0116a157ea

**Comment by znmeb** [comment]
I've run into this issue and related ones in `dpkg` with every Bookworm variant I've tried on my Zero 2 Ws. The "lock up at 33%" is just one of the symptoms; I've also seen `dpkg` spin for minutes at 100 percent CPU unpacking a large file like Firefox. There just isn't enough RAM in a Pi Zero 2 W to run Bookworm or Ubuntu 24.04 - case closed.

Making a bigger swapfile is hardly a fix; swapping to an SD card every time you upgrade is nonsensical. Realistically, I'd recommend that the Raspberry Pi Imager limit the recommended options for the Pi Zero 2 W to just Bullseye and Ubuntu 22.04. Nothing else runs out of the box with no hassles.

**Comment by Kevvie250** [comment]
> Thanks for the heads up. Looks like the dpkg fix wasn't enough in some cases and bumping swap is necessary.
> 
> I'll try defaulting to 200 instead and monitor if that's enough.
> 
> [RPi-Distro/raspberrypi-sys-mods@1f88fa7](https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/1f88fa7abe59d878920cd02582a5f1c1ec69f531) [RPi-Distro/pi-gen@75fe47c](https://github.com/RPi-Distro/pi-gen/commit/75fe47c7571c533ad52c43e03b440b0116a157ea)

Heya,

I was just trying to update a Zero 2w from a fresh install.  The hanging issue led me here.  I see that the default swapfile is now 200, not the original 100.  I still hung

The recommended OS was full 64 bit, which I did.  At fresh reboot, SWAPON showed I was at 179.   I updated it to 1024 based on a forum post.  At next reboot my swap was at 215.  Update processed without hanging (although working through a dependency error on chromium, which I assume is unrelated.)

thanks

**Comment by XECDesign** [comment]
Did you have anything else running at the time the update ran?

**Comment by Kevvie250** [comment]
Yes, VNC for headless.  Other than that, right from Imager to Zero 2W and first boot

**Comment by XECDesign** [comment]
Hmm, I don't remember the pre-6.6 kernels just locking up the whole system like that, which makes me wonder if there's some other underlying issue.

Maybe for now we do need to bump to 512 and take a look at zswap.

@popcornmix Any ideas? Is zram more appropriate? Are the default zswap parameters okay? Archlinux wiki says that [zsmalloc](https://docs.kernel.org/mm/zsmalloc.html) may be a better allocator for low-ram devices, but we're defaulting to zbud. Should we enable it at run-time when a 512MB device is detected or always?

Edit: For reference, here are the default parameters I'm seeing.
```
accept_threshold_percent 90
compressor lzo
exclusive_loads N
max_pool_percent 20
non_same_filled_pages_enabled Y
same_filled_pages_enabled Y
zpool zbud
```

**Comment by hulleyrob** [comment]
And this was closed with what successful fix? Ive tried increasing the swap to 2048 and it crashes every upgrade.

**Comment by popcornmix** [comment]
A desktop install is not recommended for 512M devices (even with swap).
There just isn't enough RAM for typical operations.

A lite image would be recommended.

**Comment by hulleyrob** [comment]
This is happening on a headless pi zero that just runs enviroplus have had to disable the apt-compat cron job because I suspect it is the cause of it hanging very often and needing to be rebooted.

**Comment by popcornmix** [comment]
I find this script useful for identifying the main memory users.
I suspect you are trying to run too much for a 512M device, or something you are running has a memory leak, and memory usage just creeps up. See what the script reports.
```
#!/bin/bash
ps -A --sort -rss -o comm,pmem,rss | awk '
  NR == 1 { print; next }
  { a[$1] += $2; b[$1] += $3; }
  END {
    for (i in a) {
      size_in_bytes = b[i] * 1024
      split("B KB MB GB TB PB", unit)
      human_readable = 0
      if (size_in_bytes == 0) {
        human_readable = 0
        j = 0
      }
      else {
        for (j = 5; human_readable < 1; j--)
          human_readable = size_in_bytes / (2^(10*j))
      }
      printf "%-20s\t%s\t%.2f%s\t%s\n", i, a[i], human_readable, unit[j+2], b[i]
    }
  }
' | awk 'NR>1' | sort -rnk4 | awk '
  BEGIN {printf "%-20s\t%%MEM\tSIZE\n", "COMMAND"} 
  {
    printf "%-20s\t%s\t%s\n", $1, $2, $3
  }
' | less
```
