### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by toreandre** [RPi-Distro/repo#36]
I use raspbian (debian jessie lite) and have some trouble with my Logitech S-150 USB speakers (raspberry pi zero)

[    9.190528] usb 1-1.3: Warning! Unlikely big volume range (=17152), cval->res is probably wrong.
[    9.190570] usb 1-1.3: [2] FU [PCM Playback Volume] ch = 2, val = 0/17152/1

The sound is distorted and sounds like an untuned FM Radio.

**Comment by XECDesign** [comment]
Doesn't look like a raspberry pi specific issue.
http://permalink.gmane.org/gmane.linux.alsa.devel/116518

Not quite sure where the correct place to report this is. Perhaps logitech themselves.
