### ISSUE TITLE
sudo apt upgrade is overwriting fix for usb-3

### ISSUE THREAD

**Issue by UgaBugaOfdeSpeer** [RPi-Distro/repo#365]
Recently I had an issue on pi-5 (bookworm : 6.1.0-rpi7-rpi-2712) : https://github.com/raspberrypi/linux/issues/5753
To solve this issue it was recommended to load an intermediate fix : 
			- sudo rpi-update pulls/5788
			- reboot
	Build before the patch : 6.1.0-rpi7-rpi-2712
	Build after the patch : 6.1.66-v8-16k+

So far so good.
Updates I did regular by doing : 
   - sudo apt update
  - sudo apt -y full-upgrade; [ -e /var/run/reboot-required ] && sudo reboot

This went well until last week.
Then I saw that the build was changed back to  6.1.0-rpi7-rpi-2712

Does that mean that the bugfix is lost?
How can this be prevented?

**Comment by XECDesign** [comment]
Right, rpi-update doesn't integrate with normal system updates in any way, it's just a tool for testing specific kernels.

You can use 'apt-mark hold' to hold packages at specific versions, or you can disable the copying of the kernel into /boot/firmware by editing /etc/default/raspi-firmware.

However, this tracker is for reporting issues with packages in the raspberry pi apt repo. For general support, the forum would be a better bet.
