### ISSUE TITLE
EOM image viewer covers the screen with certain image resolutions

### ISSUE THREAD

**Issue by Botspot** [RPi-Distro/repo#366]
This is likely a bug with EOM, but maybe with wayfire.
With an image that is 2263x2262 pixels, opening it in default PiOS 64-bit will launch an Image Viewer window that covers the screen.
![300643870-70889401-a7e7-44d8-b480-e05e7b61ba74](https://github.com/RPi-Distro/repo/assets/54716352/93ebc0a5-dc2d-42b1-a3db-2c81674a8187)

I cannot even click the Maximize button as it covers the taskbar, and the titlebar is beyond the top edge of the screen. Furthermore, there is no way to drag the window around. The only way to regain control of the system is to use Alt-F4.

I am using a normal 1080p screen - nothing special here to my knowledge.
Attached below is an image with these dimensions for others to replicate. Download the image and then open it from your Downloads folder.
[2263x2262.jpg](https://github.com/RPi-Distro/repo/assets/54716352/38365ebe-be45-4793-a7bd-eff2118a6332)
Please note that this not some crazy, artificial edge case. This happens with images using other dimensions as well, including all of the photos captured with my digital camera.

**Comment by spl237** [comment]
Wayfire, like all Wayland compositors, opens windows centred on the screen.

EOM appears to be opening images at a 1:1 pixel mapping by default, and this image is larger than your screen in the vertical dimension, so a centred EOM window has the top and bottom outside the visible screen area.

There's nothing that can be done in Wayfire to fix this. I'd suggest that the EOM developers might want to change the default scaling with which an image is opened if an image is larger than a certain size, ideally based on monitor dimensions. I suggest you raise an issue at https://github.com/mate-desktop/eom

**Comment by Botspot** [comment]
The strange thing here is that 2262x2262 works and 2263x2263 works - they open in a reduced zoom level.
I suspect this is more nuanced, but will try to get someone on the eom repo to reproduce it.
