### ISSUE TITLE
f2fs module missing 6.6.20v8

### ISSUE THREAD

**Issue by Emimendoza** [RPi-Distro/repo#370]
The package:
`linux-image-6.6.20+rpt-rpi-v8_6.6.20-1+rpt1_arm64.deb`
Does not include the f2fs module. The .config provided in the package (and the default one in [https://github.com/raspberrypi/linux/](url) )says it should be there and it also states that the pages are 4k so it isn't the 16k page issue that causes the 2712 kernels to not have it. It is just a case of the package being built/packaged incorrectly

**Comment by popcornmix** [comment]
What do you see when you run:
```
sudo modprobe configs 
zcat /proc/config.gz  | grep F2FS
```

**Comment by XECDesign** [comment]
Looks like it's compiled in rather than a module - https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm64/configs/bcm2711_defconfig#L1522

**Comment by Emimendoza** [comment]
Turns out I was still booting 2712 by accident. Can confirm f2fs is built into the kernel not as a module. Thanks yall
