### ISSUE TITLE
drbl depends on syslinux - alternative?

### ISSUE THREAD

**Issue by vanguard2016** [RPi-Distro/repo#38]
Dear maintainers,

as there is no package "syslinux" available (which was first mentioned 3 years ago and could still not be fixed), is there an alternative for this?

I wanted to install drbl and clonezilla, but drbl depends on syslinux. So drbl and clonezilla cannot be installed. But maybe you can change the dependencies of drbl from syslinux to (existing) syslinux-efi in the repo?

Doing so should one to be enable, to install drbl and clonezilla. And I believe, syslinux-efi will do the same as syslinux (maybe better). However, this needs to change the deps in your repo.

Hope this can be done without any harm.

Thanks for reading this.

Best regards

Hans-J. Ullrich

**Comment by XECDesign** [comment]
As suggested [here](https://github.com/raspberrypi/linux/issues/1591), Raspbian bugs go [here](https://www.raspbian.org/RaspbianBugs).
This repo is for packages in the raspberrypi.org repo, not raspbian.org. If you would like us to include an updated drbl in raspberrypi.org, you'd need to confirm that syslinux-efi works at all on the pi and that clonezilla functions as intended. I would be very surprised if that's the case. AFAIK, syslinux will only work on x86 systems. I suspect syslinux-efi is intended to be used with a tftp server to boot x86 systems off.
