### ISSUE TITLE
/etc/os-release should specify NAME as 'Raspberry Pi OS'

### ISSUE THREAD

**Issue by andrum993** [RPi-Distro/repo#381]
Firstly, apologies if this is not a good place for this issue - it seemed like the most appropriate place to raise this.

The file `/etc/os-release` currently reports different values for NAME in the 32-bit version of Raspberry Pi OS, compared to the 64-bit version. On 32-bit it reports `Raspbian GNU/Linux`, while on 64-bit it reports `Debian GNU/Linux`. In each case this is due to that version of Raspberry Pi OS being based on Raspbian (32-bit) and Debian (64-bit).

This issue is to propose that both be changed to read `Raspberry Pi OS`. This would make it clear when the machine boots that Raspberry Pi OS is the running OS. The documentation for the `/etc/os-release` file - https://www.freedesktop.org/software/systemd/man/latest/os-release.html - does not specify whether this variable needs to be the actual distro name or not; I would argue that doing so is a good thing as it avoids any ambiguity. (It also has the handy property of removing what is hopefully the last instance of `Raspbian` from the Raspberry Pi OS UI).

Note that if this proposal is accepted, it will also be necessary to make similar changes to the PRETTY_NAME variable in the same file, and to both NAME and PRETTY_NAME in the `/var/lib/os-release` file.

A further enhancement would be to use the optional, currently unused, VARIANT variable to specify whether the OS was 32-bit or 64-bit. There can be confusion as to whether a user is running the 32-bit or 64-bit version of the OS, due to the presence of 64-bit kernels on the 32-bit distro. Specifying the architecture here would provide a single known-good reference for which architecture the system is running. Note that for the purposes of this discussion, the meaning of "architecture" is the userland bit width, i.e. 32 or 64 bit. (It's already easy to find out the kernel architecture).

**Comment by XECDesign** [comment]
That would break way too many scripts out there which are usually just checking whether they're running on Debian or Ubuntu.

**Comment by andrum993** [comment]
> That would break way too many scripts out there which are usually just checking whether they're running on Debian or Ubuntu.

Which are presumably broken on Raspbian already. Is this file the best and recommended place to determine the running distro?

I don't have a strong view on this, but I thought it was worth raising this issue.

**Comment by popcornmix** [comment]
> Is this file the best and recommended place to determine the running distro?

I'd suggest checking for /etc/rpi-issue if you want to know if you are running on RPiOS.

**Comment by andrum993** [comment]
OK, so it sounds like the best thing is to leave this file as it is. Thank you both for your input; I will close this issue.

**Comment by XECDesign** [comment]
> Which are presumably broken on Raspbian already.

Raspbian started with their own version of that file, so scripts were written with that in mind from the start. Although I still ocasionally see cases where it causes issues.

I'd rethink why you need to know that in the first place. If you need to know something about the kernel you're running, use `uname`. If you need to know the architecture of userland packages, use `dpkg --print-architecture` and so on. I can't think of many cases where software needs to do something different based on whether it's running under Raspberry Pi OS or Debian. 

Whatever the difference between the two is that makes your software want to behave differently is the thing I'd be checking for directly.

**Comment by andrum993** [comment]
Apologies. My issue with the current file contents was that at boot up Raspberry Pi OS misidentifies itself as either Raspbian or Debian, however I had misunderstood where this is set. To me the CLI should state `Raspberry Pi OS` at boot, not `Raspbian GNU/Linux` or `Debian GNU/Linux`. I think it would have been preferrable if Raspberry Pi had made this change when Raspberry Pi OS was first released, as Raspbian had done at some point (I seem to remember it was not done immediately by Raspbian).

Do you think there is any mileage in suggesting that Raspberry Pi OS change the OS name reported in /etc/issue to `Raspberry Pi OS`?

**Comment by XECDesign** [comment]
I am not against updating `/etc/issue`. I've actually been meaning to make it show the IP address as well, so I'll do that when I get a chance.

**Comment by XECDesign** [comment]
Unfortunately `/etc/issue` comes from base-files as well, which I don't want to adopt as a Raspberry Pi OS package. I can't override the file using `dpkg-divert` since it specifically says it shouldn't be used for conffiles.

There's /etc/issue.d for adding additional text, which I can use for the IP thing, but it doesn't really help with what's already in /etc/issue.

Another alternative could be to add `--issue-file /etc/issue.pios` to `agetty`, but messing with `ExecStart` in a drop-in service file is going to be a minefield. For example, if somebody has autologin enabled, the same mechanism is used. So they'll either not get the new issue file or autologin will stop working.

I'm not seeing a nice way to do it and it's not enough of an issue to be worth messing with the edge cases in postinst. At the end of the day, whether it says Raspberry Pi OS, Raspbian or Debian, it's not wrong.

**Comment by andrum993** [comment]
No problem - thanks for considering it.
