### ISSUE TITLE
adb on RPi0 produces an "Illegal instruction" error (issue with libcrypto.so.0)

### ISSUE THREAD

**Issue by 0awe** [RPi-Distro/repo#384]
Hopefully this is the correct place to report this issue.

libcrypto.so.0, part of android-libboringssl library package, included with adb install, does not work on brand new install of Bookworm on Raspberry Pi Zero W Rev 1.1. The library causes adb to generate an "Illegal instruction" error.

The following is mostly copied from links mentioned at the bottom of this post.

```
cat /proc/cpuinfo
processor : 0
model name : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS : 697.95
Features : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part : 0xb76
CPU revision : 7

Hardware : BCM2835
Revision : 9000c1
Serial : 00000000b1625db5
Model : Raspberry Pi Zero W Rev 1.1
```
ADB installed via `sudo apt-get install adb`.

Executing adb from bash shell generates "Illegal instruction" error.

Running (r) "gdb adb" results in the following output.

```
(gdb) r
Starting program: /usr/bin/adb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb6e7b3cc in ?? () from /usr/lib/arm-linux-gnueabihf/android/libcrypto.so.0
(gdb)
```

Checking the android-libboringssl library:

```
sudo apt-cache policy android-libboringssl
android-libboringssl:
  Installed: 13.0.0+r24-2+rpi1
  Candidate: 13.0.0+r24-2+rpi1
  Version table:
 *** 13.0.0+r24-2+rpi1 500
        500 http://raspbian.raspberrypi.com/raspbian bookworm/main armhf Packages
        100 /var/lib/dpkg/status
```

And its contents:

```
sudo dpkg-query -L android-libboringssl
/.
/usr
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/android
/usr/lib/arm-linux-gnueabihf/android/libcrypto.so.0
/usr/lib/arm-linux-gnueabihf/android/libssl.so.0
/usr/share
/usr/share/doc
/usr/share/doc/android-libboringssl
/usr/share/doc/android-libboringssl/INCORPORATING.md.gz
/usr/share/doc/android-libboringssl/NOTICE.gz
/usr/share/doc/android-libboringssl/README.Debian
/usr/share/doc/android-libboringssl/README.md
/usr/share/doc/android-libboringssl/changelog.Debian.gz
/usr/share/doc/android-libboringssl/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/android-libboringssl
```

Workaround is to download and install an older version of libcrypto.so.0.

```
cd /tmp
curl -O http://rpi.rutgers.edu/raspbian/raspbian/pool/main/a/android-platform-external-boringssl/android-libboringssl_10.0.0+r36-1+rpi1_armhf.deb
dpkg-deb -x android-libboringssl_10.0.0+r36-1+rpi1_armhf.deb .
cd /usr/lib/arm-linux-gnueabihf/android
sudo mv libcrypto.so.0 libcrypto.so.0_ORIG
sudo mv /tmp/usr/lib/arm-linux-gnueabihf/android/libcrypto.so.0 .
sudo chown root:root libcrypto.so.0

```

This issue has been reported elsewhere without any action taken:

[https://github.com/raspberrypi/bookworm-feedback/issues/261](https://github.com/raspberrypi/bookworm-feedback/issues/261)
[https://bugs.launchpad.net/raspbian/+bug/2091145](https://bugs.launchpad.net/raspbian/+bug/2091145)

Thank you for looking into this.

**Comment by ghollingworth** [comment]
The issue is either with the upstream package (for example it has binaries in it that do not support armv6), or the Raspbian rebuild of this (the raspbian repo is supported and maintained outside of Raspberry Pi)

https://raspbian.org/
