### ISSUE TITLE
/raspbian/pool/main/l/linux-3.10/

### ISSUE THREAD

**Issue by fgndevelop** [RPi-Distro/repo#41]
Hi all,

I am running a repository mirror for my Pi-based intranet. Hence I generate package index files using 
apt-ftparchive and it complains about a gzip-error with 
/raspbian/pool/main/l/linux-3.10/linux-source-3.10_3.10.11-1+rpi7_all.deb
Checking the archive I found that indeed, apt-ftparchive is right. The file "data.tar.gz" from the above linux source .deb file claims to be gzipped - but isn't. Maybe this can be fixed. 

Thanks a lot for the great work, 

Frank

**Comment by XECDesign** [comment]
This repo is for packages from raspberrypi.org, not raspbian.org. Raspbian.org problems can be reported here https://www.raspbian.org/RaspbianBugs
