### ISSUE TITLE
Ugly colour banding with gstreamer video

### ISSUE THREAD

**Issue by herrernst** [RPi-Distro/repo#43]
I've tried to use `gst123` or `gst-launch playbin` (which is then probably using glimagesink) to play videos on the terminal instead of omxplayer (with gstreamer1.0-omx hardware acceleration). I works almost good (no stuttering), but I get considerable colour banding, which does not occur with omxplayer. Is there anything I can do about it? Thanks

**Comment by XECDesign** [comment]
Unfortunately gstreamer is no longer maintained.

**Comment by gkreidl** [comment]
That's not true and a lot of Raspbian packages depend on gstreamer packages.

**Comment by XECDesign** [comment]
I should've worded that clearer. The collabora omx patches are not maintained.

**Comment by gkreidl** [comment]
I hope you will leave it unchanged, at least, because the current version contains some patches which I have sent them to fix some bad memory leaks.

**Comment by XECDesign** [comment]
No plans to touch it in jessie. No idea what will happen in stretch.

**Comment by herrernst** [comment]
I just wanted to say that I am not happy that gstreamer omx will not be maintained anymore, gstreamer being a widely used library.

**Comment by XECDesign** [comment]
I know, it's not the best situation. But it looks like gst-omx is still maintained upstream, so it may be worthwhile looking at how stable that is and whether it can be merged back into Raspbian.

**Comment by gkreidl** [comment]
And I definitely need it. It's the backbone of my real time TV transcoding package.

**Comment by XECDesign** [comment]
@gkreidl, how does upstream compare to what's in the repo as far as stability and performance goes?

**Comment by gkreidl** [comment]
I don't know. I'm still using Jessie version. There was a memory leak in gst-omx and I've sent a fix from upstream to the collabora people and they applied that patch (it's in the current version). I also tried to compile a 1.2 version which never worked. There's a script on github to compile latest versions and someone on the forum said he got it to work including gst-omx, but I haven't tried it myself.
https://gist.github.com/sphaero/02717b0b35501ad94863

**Comment by fnoop** [comment]
I'm trying to get upstream (1.10.3) gst-omx working.  I get it compiled fine but it hangs when doing any encoding.  Are the collabora patches available somewhere to look at?

**Comment by XECDesign** [comment]
@fnoop http://archive.raspberrypi.org/debian/pool/main/g/gst-omx1.0/gst-omx1.0_1.0.0.1-0+rpi18.debian.tar.xz

**Comment by fnoop** [comment]
Thanks :)  I'm surprised upstream doesn't work with raspberry, there's so much reference in recent changelogs.

**Comment by gkreidl** [comment]
Obviously a lot of upstream code (gst_omx) has never been tested on a Raspberry Pi. I couldn't even get version 1.2 (including patches from collabora) to work.

**Comment by fnoop** [comment]
What source does this apply to?  I've tried applying to the original 1.0.0 source release and half the patch chunks fail.

**Comment by fnoop** [comment]
Ah found it the archive directory, sorry:
http://archive.raspberrypi.org/debian/pool/main/g/gst-omx1.0/gst-omx1.0_1.0.0.1.orig.tar.xz

**Comment by gkreidl** [comment]
I pulled the sources from the collabora git.

**Comment by fnoop** [comment]
OK found branch rpi-1.0.0.1 in https://git.collabora.com/cgit/raspberry-pi/gst-omx.git/ that seems to be patched source.  Sigh, this doesn't compile against recent gstreamer releases (I'm trying 1.10.3).  
Really sad that raspberry is completely stalled on gstreamer..
