### ISSUE TITLE
Broken dependencies of dev packages

### ISSUE THREAD

**Issue by gkreidl** [RPi-Distro/repo#48]
After installing the latest updates a number of dev packages have broken dependencies:

libxfont-dev: Depends on: libxfont1 (=1:1.5.1-1), but 1:1.5.2-1 will be installed

libva-dev: Depends on: libva1 (=1.4.1-1), but 1.7.2-1 will be installed

As a result other dev-packages are also broken, because they depend on libxfont-dev, e. g. xserver-xorg-dev

Compiling packages depending on those dev packages, e. g. VLC, is not possible at the moment.

**Comment by XECDesign** [comment]
Thanks, this should be fixed now.
