### ISSUE TITLE
xserver-xorg-legacy Not Installable

### ISSUE THREAD

**Issue by bnielsen1965** [RPi-Distro/repo#49]
Cannot install the xserver-xorg-legacy package on an updated Raspbian system...

> The following packages have unmet dependencies:
>  xserver-xorg-legacy : Breaks: x11-common (< 1:7.7+10~) but 1:7.7+7 is installed.

Cannot upgrade x11-common using apt-get to a version that will allow installation of xserver-xorg-legacy.

**Comment by XECDesign** [comment]
Should be resolved

**Comment by bnielsen1965** [comment]
Confirmed, fixed. The package now installs as expected and my package that depends on legacy support now works as expected. A big thanks!

**Comment by XECDesign** [comment]
Thanks for confirming.

**Comment by ybendou** [comment]
Seems that the problem is up again, cannot install xserver-xorg-legacy package on amd64 :+1: 
The following packages have unmet dependencies:
 xserver-xorg-legacy : Breaks: x11-common (< 1:7.7+10~) but 1:7.7+7 is to be installed.

I can't upgrade too to a newer version of x11-common with apt-get
