### ISSUE TITLE
multiple packages/commands  segfault after apt-get upgrade

### ISSUE THREAD

**Issue by topfer** [RPi-Distro/repo#53]
thf@opsberry ~ $ uname -a
Linux opsberry 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
thf@opsberry ~ $ /opt/vc/bin/vcgencmd version
Mar 15 2016 14:51:23 
Copyright (c) 2012 Broadcom
version 1bf9a9a77026af9128a339c82d72e331d3532ee4 (clean) (release)
Segmentation fault (core dumped)

As title suggest multiple commands end in Segmentation fault and core dump (thinks like a bash, gdb, apt or even vcgencmd as you can see in the listing above)
I don't thing that it is a hardware(SD card problem) because the issue appeared imediately after "apt-get upgrade"

I attach one example core file related to the vcgencmd command from the listing above
[core.zip](https://github.com/RPi-Distro/repo/files/701124/core.zip)

**Comment by XECDesign** [comment]
Running apt-get upgrade results in a lot of IO, which would indicate that it IS an sd card issue? Would you happen to know the make and model of the card? If you start with a fresh image and add `mmc_card.quirks=0x80000000` to cmdline.txt, does the upgrade succeed?
