### ISSUE TITLE
autofs is missing lookup_sss.so while interacting with sssd

### ISSUE THREAD

**Issue by pavebul** [RPi-Distro/repo#54]
autofs 5.0.8-2+deb8u1
I use RaspberryPi as a domain controller.

Among other things I store home directories at NFS file server.
To get maps autofs shoud ask sssd. But when autofs starts I get:
`open_lookup:93: cannot open lookup module sss (/usr/lib/arm-linux-gnueabihf/autofs/lookup_sss.so: cannot open shared object file: No such file or directory)`

I've got similar problem at my desktop Debian system. Installing autofs 5.1.1-1 has helped. Now autofs looks for correct module path, which is:
`/usr/lib/arm-linux-gnueabihf/sssd/modules/libsss_autofs.so`

I consider this is a bug.
Related bugs:
http://debian.2.n7.nabble.com/Bug-762843-lookup-sss-so-missing-fixed-in-the-unreleased-5-0-8-2-version-td3492919.html
https://bugs.launchpad.net/linuxmint/+bug/1081489

PS:
I've tried to install autofs from testing repo, but it wants some dependencies:
```
$ sudo apt-get install autofs-ldap/testing
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '5.1.2-1' (Raspbian:testing [armhf]) for 'autofs-ldap'
Selected version '1.15-1' (Raspbian:testing [armhf]) for 'libkrb5-3' because of 'autofs-ldap'
Selected version '1.15-1' (Raspbian:testing [armhf]) for 'libk5crypto3' because of 'libkrb5-3'
Selected version '1.15-1' (Raspbian:testing [armhf]) for 'libkrb5support0' because of 'libk5crypto3'
Selected version '5.1.2-1' (Raspbian:testing [armhf]) for 'autofs' because of 'autofs-ldap'
The following packages were automatically installed and are no longer required:
  libavahi-core7 libdaemon0 libev4 librtmp1 libverto-libev1 libverto1 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 ncurses-term xauth
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  autofs libk5crypto3 libkrb5-3 libkrb5support0
Suggested packages:
  krb5-doc
Recommended packages:
  krb5-locales
The following packages will be REMOVED:
  avahi-daemon bind9 bind9-host bind9utils curl krb5-admin-server krb5-config krb5-kdc krb5-user libbind9-90 libcups2 libcurl3 libdns100 libgssapi-krb5-2 libgssrpc4
  libisccfg90 libkadm5clnt-mit9 libkadm5srv-mit9 libkdb5-7 libnss-mdns libpam-krb5 libsasl2-modules-gssapi-mit libtirpc1 nfs-common openssh-client openssh-server
  openssh-sftp-server rpcbind rsyslog-gssapi samba-libs ssh sssd sssd-ad sssd-ad-common sssd-ipa
The following packages will be upgraded:
  autofs autofs-ldap libk5crypto3 libkrb5-3 libkrb5support0
5 upgraded, 0 newly installed, 35 to remove and 2 not upgraded.
Need to get 948 kB of archives.
After this operation, 30.7 MB disk space will be freed.
Do you want to continue? [Y/n] 
```
This is not what I really want. I'm afraid these changes can break something.

**Comment by XECDesign** [comment]
Given that 5.0.8-2+deb8u1 is the current version in Debian Jessie, I don't think this is a Raspbian or Raspberry Pi issue. If Debian bumps the version in Jessie, that will be reflected in Raspbian.
