### ISSUE TITLE
spice-client package is available in jessie but ommited as part of Raspbian

### ISSUE THREAD

**Issue by trixpan** [RPi-Distro/repo#55]
https://packages.debian.org/jessie/spice-client

but apt-get install spice-client fails

**Comment by dotysan** [comment]
Notice on that page there are no ARM builds in Jessie. Only amd64 and i386 builds.

**Comment by XECDesign** [comment]
That might be a question to raise with the package's maintainer, but it's not really related to the raspberrypi.org repo.
