### ISSUE TITLE
Missing dependencies for wolfram-engine

### ISSUE THREAD

**Issue by appleorange1** [RPi-Distro/repo#57]
libxmu6 and libglu1-mesa are necessary for mathematica to work, but these are not dependencies of wolfram-engine.

**Comment by XECDesign** [comment]
Ping @spl237

**Comment by spl237** [comment]
I'll raise it with Wolfram.

**Comment by appleorange1** [comment]
Thanks!

**Comment by XECDesign** [comment]
Looks like this is fixed.
