### ISSUE TITLE
No archive keyring package.

### ISSUE THREAD

**Issue by ali1234** [RPi-Distro/repo#59]
For example, raspbian has raspbian-archive-keyring. There is collabora-rpifoundation-archive-keyring, but it doesn't seem to contain the key used to sign the packages.

This is needed by various bootstrapping tools in order to verify packages.

**Comment by XECDesign** [comment]
Added a raspberrypi-archive-keyring package

**Comment by ali1234** [comment]
Works fine with multistrap. Thanks.
