### ISSUE TITLE
New Kodi 17.1 package - cannot select attached DAC as audio output

### ISSUE THREAD

**Issue by ghost** [RPi-Distro/repo#64]
On the new Kodi 17.1 package for Jessie that just appeared in the repo I am unable to select my attached IQAudio Pi-DAC+ as an output source. I was previously using Kodi 16.1 from archive.mene.za.net which does have this option, along with the usual Pi outputs (HDMI, analogue, HDMI and analogue). Please add the option to output to an attached DAC via ALSA, like the Kodi version from archive.mene.za.net has.

**Comment by XECDesign** [comment]
Closing in favour of this thread, since the package comes from an external source:
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=180626&p=1148755#p1147953
