### ISSUE TITLE
Unable to use more than 2 'Atheros AR9271' WiFi Dongles

### ISSUE THREAD

**Issue by pi-resource** [RPi-Distro/repo#67]
More than two WiFi Dongel with the Atheros AR9271 chipsets are not identified. In this example I used a TP-LINK TL-WN722N. I can confirm there were NO power issues. See dmesg outputs below.

First device plugged in: (all normal)
[ 3626.648706] usb 1-1.2.1: new high-speed USB device number 6 using dwc_otg
[ 3626.799647] usb 1-1.2.1: New USB device found, idVendor=0cf3, idProduct=9271
[ 3626.799661] usb 1-1.2.1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 3626.799669] usb 1-1.2.1: Product: USB2.0 WLAN
[ 3626.799677] usb 1-1.2.1: Manufacturer: ATHEROS
[ 3626.799684] usb 1-1.2.1: SerialNumber: 12345
[ 3627.944779] usb 1-1.2.1: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[ 3627.944907] usb 1-1.2.1: Direct firmware load for ath9k_htc/htc_9271-1.4.0.fw failed with error -2
[ 3627.944922] usb 1-1.2.1: ath9k_htc: Firmware htc_9271.fw requested
[ 3627.945481] usbcore: registered new interface driver ath9k_htc
[ 3628.241745] usb 1-1.2.1: ath9k_htc: Transferred FW: htc_9271.fw, size: 51272
[ 3628.487600] ath9k_htc 1-1.2.1:1.0: ath9k_htc: HTC initialized with 33 credits
[ 3633.007736] ath9k_htc 1-1.2.1:1.0: ath9k_htc: FW Version: 1.3
[ 3633.007748] ath9k_htc 1-1.2.1:1.0: FW RMW support: Off
[ 3633.007755] ath: EEPROM regdomain: 0x809c
[ 3633.007759] ath: EEPROM indicates we should expect a country code
[ 3633.007764] ath: doing EEPROM country->regdmn map search
[ 3633.007769] ath: country maps to regdmn code: 0x52
[ 3633.007775] ath: Country alpha2 being used: CN
[ 3633.007779] ath: Regpair used: 0x52
[ 3633.034162] ieee80211 phy1: Atheros AR9271 Rev:1
[ 3633.899923] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready

Second device plugged in: (Normal)
[ 3678.808836] usb 1-1.2.2: new high-speed USB device number 7 using dwc_otg
[ 3678.959885] usb 1-1.2.2: New USB device found, idVendor=0cf3, idProduct=9271
[ 3678.959899] usb 1-1.2.2: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 3678.959907] usb 1-1.2.2: Product: USB2.0 WLAN
[ 3678.959915] usb 1-1.2.2: Manufacturer: ATHEROS
[ 3678.959940] usb 1-1.2.2: SerialNumber: 12345
[ 3678.961096] usb 1-1.2.2: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[ 3678.962086] usb 1-1.2.2: Direct firmware load for ath9k_htc/htc_9271-1.4.0.fw failed with error -2
[ 3678.962102] usb 1-1.2.2: ath9k_htc: Firmware htc_9271.fw requested
[ 3679.255303] usb 1-1.2.2: ath9k_htc: Transferred FW: htc_9271.fw, size: 51272
[ 3679.500607] ath9k_htc 1-1.2.2:1.0: ath9k_htc: HTC initialized with 33 credits
[ 3682.993741] ath9k_htc 1-1.2.2:1.0: ath9k_htc: FW Version: 1.3
[ 3682.993753] ath9k_htc 1-1.2.2:1.0: FW RMW support: Off
[ 3682.993760] ath: EEPROM regdomain: 0x809c
[ 3682.993765] ath: EEPROM indicates we should expect a country code
[ 3682.993769] ath: doing EEPROM country->regdmn map search
[ 3682.993775] ath: country maps to regdmn code: 0x52
[ 3682.993780] ath: Country alpha2 being used: CN
[ 3682.993784] ath: Regpair used: 0x52
[ 3683.005653] ieee80211 phy2: Atheros AR9271 Rev:1
[ 3683.869106] IPv6: ADDRCONF(NETDEV_UP): wlan2: link is not ready

Third and subsequent devices: (ERRORS)
[ 3826.729283] usb 1-1.2.4.1: new high-speed USB device number 8 using dwc_otg
[ 3826.880406] usb 1-1.2.4.1: New USB device found, idVendor=0cf3, idProduct=9271
[ 3826.880420] usb 1-1.2.4.1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 3826.880453] usb 1-1.2.4.1: Product: USB2.0 WLAN
[ 3826.880461] usb 1-1.2.4.1: Manufacturer: ATHEROS
[ 3826.880469] usb 1-1.2.4.1: SerialNumber: 12345
[ 3826.881665] usb 1-1.2.4.1: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[ 3826.883288] usb 1-1.2.4.1: Direct firmware load for ath9k_htc/htc_9271-1.4.0.fw failed with error -2
[ 3826.883344] usb 1-1.2.4.1: ath9k_htc: Firmware htc_9271.fw requested
[ 3827.176355] usb 1-1.2.4.1: ath9k_htc: Transferred FW: htc_9271.fw, size: 51272
[ 3828.429300] usb 1-1.2.4.1: Service connection timeout for: 256
[ 3828.429347] ath9k_htc 1-1.2.4.1:1.0: ath9k_htc: Unable to initialize HTC services
[ 3828.429374] ath9k_htc: Failed to initialize the device
[ 3828.431265] usb 1-1.2.4.1: ath9k_htc: USB layer deinitialized

all devices are shown with the 'lsusb' command

**Comment by XECDesign** [comment]
This looks like a kernel issue and should be reported here:
https://github.com/raspberrypi/linux/issues
