### ISSUE TITLE
Missing source for packages

### ISSUE THREAD

**Issue by ydirson** [RPi-Distro/repo#7]
Eg. http://archive.raspberrypi.org/debian/pool/main/g/gst-plugins-bad1.0/ has only an old version of the source.  And there must be a deeper problem allowing to get into that inconsistent state.

**Comment by em-** [comment]
Apparently the sources haven't been uploaded to the Foundation archive. You can provisionally find them in the [deprecated Collabora archive](http://raspberrypi.collabora.com/pool/web/g/gst-plugins-bad1.0/).

**Comment by ydirson** [comment]
Great, thanks much! 

----- Mail original -----

**Comment by XECDesign** [comment]
Thanks, grabbed the source from the collabora repo and add it later. It seems that the package was built without the -sa flag, so when it was uploaded to our repo the original source wasn't included and the source package had to be skipped. Shouldn't happen in the future.
