### ISSUE TITLE
"/bin/ping -I" does not work correctly when invoked by cron

### ISSUE THREAD

**Issue by whunder** [RPi-Distro/repo#71]
The command "/bin/ping" works when invoked by cron, but when "/bin/ping -I" is invoked by cron the command fails. I can run this same code from the command line with success. Here is a snippet of my code that has been causing the issue. Output from uname -a "Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux"

`# IP Forwarding check
LANIP=$( ifconfig eth0 | grep "inet " | awk -F'[: ]+' '{ print $4 }' )
WLANIP=$( ifconfig wlan0 | grep "inet " | awk -F'[: ]+' '{ print $4 }' )

LANTOWLAN=$( /bin/ping -c5 -I "$LANIP" "$WLANIP" > /dev/null && echo 0 )
echo "Internal IP forwarding check on `date`." >> /home/pi/Desktop/connection.log
if [ "$LANTOWLAN" == 0 ]
then
	echo "IP Forwarding from LAN to WLAN is working!" >> /home/pi/Desktop/connection.log
	echo "" >> /home/pi/Desktop/connection.log
else
	echo "IP Forwarding from LAN to WLAN is not working!" >> /home/pi/Desktop/connection.log
	echo "" >> /home/pi/Desktop/connection.log
fi`

**Comment by XECDesign** [comment]
I would recommend posting the question on the forum (https://www.raspberrypi.org/forums), since it's not related to the raspberrypi.org repo.
