### ISSUE TITLE
pypy-smbus-cffi: broken dependencies

### ISSUE THREAD

**Issue by akkana** [RPi-Distro/repo#72]
Raspbian says this bug: https://bugs.launchpad.net/raspbian/+bug/1702346 should be moved here.

The pypy-smbus-cffi package can't be installed in Raspbian because of broken dependencies:

$ sudo apt-get install pypy-smbus-cffi
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pypy-smbus-cffi : PreDepends: pypy-upstream (< 2.3) but 4.0.1+dfsg-1+rpi1 is to be installed
                   PreDepends: pypy-upstream-dev (>= 2.2) but it is not going to be installed
                   PreDepends: pypy-upstream-dev (< 2.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I don't have any held packages:
$ dpkg --get-selections | grep hold
shows nothing. I don't have any nonstandard repos in /etc/apt/sources.list* either.

**Comment by XECDesign** [comment]
It looks like that software either doesn't support or is not packaged for more recent versions of pypy.
I'd recommend raising the issue here:
https://github.com/bivab/smbus-cffi

For now, I will pull the package from the repo.
