### ISSUE TITLE
dnsmasq in stretch built against jessie libraries.

### ISSUE THREAD

**Issue by plugwash** [RPi-Distro/repo#73]
dnsmasq in your stretch repo is built against the jessie libraries. It needs rebuilding for the stretch libraries.

Orignal report at https://bugs.launchpad.net/raspbian/+bug/1704621

**Comment by XECDesign** [comment]
Thanks for the heads up.

**Comment by XECDesign** [comment]
Should be fixed now.

**Comment by bwduncan** [comment]
Sorry for reopening a long dead bug but this doesn't seem to be fixed in raspbian stretch. Should the bug be bumped in the raspbian bug tracker instead?

**Comment by benjaminreichDE** [comment]
@bwduncan I am the orignal bug reporter. My dependencies are okay. Try  "apt-cache depends dnsmasq-base" and paste your result here.

**Comment by bwduncan** [comment]
Sorry, my mistake. I had updated /etc/apt/sources.list but not /etc/apt/sources.list.d/raspi.list. Apologies for the noise!
