### ISSUE TITLE
Pi3 Dhcpcd.conf file setting for static ipv6

### ISSUE THREAD

**Issue by Richaagarwalrn** [RPi-Distro/repo#75]
I am trying to do static ipv6 on pi3...should I disable slaac option. ..And how to do configuration for the same in dhcpcd.conf file

**Comment by XECDesign** [comment]
This is probably a question for the forum of the dhcpcd mailing list.

**Comment by s1awa** [comment]
@Richaagarwalrn https://raspberrypi.stackexchange.com/a/37921
