### ISSUE TITLE
Please build a Kodi package for Stretch

### ISSUE THREAD

**Issue by andrum99** [RPi-Distro/repo#77]
The Kodi package in this (archive.raspberrypi.org) repo works well on Jessie. The RPF just released a Stretch-based distro, and unfortunately the version that is being pulled in from the Raspbian repo (not this repo) is a bit broken - it uses X, is rather slow, and the startup script is borked.

This is a feature request to have a new Kodi package in this repo for Stretch. The provision of a systemd service script would be nice as well - you should be able to use the one for the Raspbian package as a template.

**Comment by LeSpocky** [comment]
I can confirm `kodi -fs --standalone` does not work anymore but crashes with "GUI not found". In the log it seems he tries to find an X server but can't. Starting from X is terribly slow on RPi2, taking several seconds for one keystroke to be reacted on. 😞

**Comment by XECDesign** [comment]
Updated version of kodi from Rascas has been added to the repo.

**Comment by LeSpocky** [comment]
**Note:** upgrading from the previous kodi package fails. You have to remove it first and then install it again.

**Comment by andrum99** [comment]
Is there a suitable systemd startup script?
