### ISSUE TITLE
adduser does not create mailbox file automatically on Raspbian Stretch lite

### ISSUE THREAD

**Issue by antoniosk** [RPi-Distro/repo#82]
It seems that the option CREATE_MAIL_SPOOL=yes in /etc/default/useradd is ignored. The expected behaviour is to create a file /var/mail/<username>. This is how it works in Raspbian Jessie.

Workaround: create the mailbox manually and set the permissions as follows (filename and username are the same):
chown <username>:mail <filename>
chmod 600 <filename>

Raspbian Stretch lite was installed using dd command with image released on 2017-08-16.

**Comment by XECDesign** [comment]
Any idea what the behaviour in regular Debian Stretch is?

**Comment by antoniosk** [comment]
Debian Stretch has the same problem.

**Comment by XECDesign** [comment]
This repo is for issues that originate in the raspberrypi.org apt repo, so this should probably reported here instead:
https://www.debian.org/Bugs/Reporting

**Comment by antoniosk** [comment]
Will do, thank you.

**Comment by XECDesign** [comment]
Thanks
