### ISSUE TITLE
Blas broken on pi1 by your updates

### ISSUE THREAD

**Issue by plugwash** [RPi-Distro/repo#83]
A user reported that blas is now broken on pi1 due to the updates you shipped to it.

https://bugs.launchpad.net/raspbian/+bug/1700510

He has provided a testcase, but I have not checked myself if I can reproduce it

**Comment by XECDesign** [comment]
Thanks for passing it on. Although Pi 1 is still supported, Jessie no longer is. Blas libs are left untouched in Stretch. To help avoid this sort of thing in the future, I'll run builds through your armv7 contamination check.
