### ISSUE TITLE
chromium-browser: missing dependency

### ISSUE THREAD

**Issue by puck** [RPi-Distro/repo#84]
Hey,

The chromium-browser in Raspbian Stretch is missing a package dependency on libgtk-3-0.

Error display when running chromium-browser from the command line:
/usr/lib/chromium-browser/chromium-browser: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

Cheers,
Andrew

**Comment by XECDesign** [comment]
Thanks. This is probably not enough to warrant a rebuild, but it should be added for the next build.

@kusti8 (who kindly provides us with the .deb's), could this be added?

**Comment by runboy93** [comment]
chromium-browser_60.0.3112.113-0ubuntu0.14.04.1194_armhf.deb

**Comment by kusti8** [comment]
Done!

**Comment by XECDesign** [comment]
That was quick.

Thanks!

**Comment by puck** [comment]
Awesome!

**Comment by theHilikus** [comment]
Any idea when this fixed package will be in the repos?

**Comment by wturnerharris** [comment]
Is there a merge request or something for this? I just had to manually install libgtk-3-0 manually. Not that it's terribly hard to do, but it would be helpful to simply install.

**Comment by XECDesign** [comment]
Is the issue resolved?

**Comment by kusti8** [comment]
A new version hasn't come out yet, so I haven't rebuilt it. I can build it if you need it.

**Comment by XECDesign** [comment]
I've manually adjusted the existing .deb because there was another issue with it. AFAIK, the version that's currently in the repo should have this issue addressed.
