### ISSUE TITLE
networking and dhcpcd are both enabled by default

### ISSUE THREAD

**Issue by s1awa** [RPi-Distro/repo#86]
After installing Rasbian on Raspberry PI 1 Model B+ and updating to the latest Stretch version
`sudo apt dist-upgrade`
Both networking and dhcpcd services are running by default.
This messes with custom network configuration.

After disabling networking
`sudo systemctl disable networking`
my dhcpcd configuration for a static IP finally started working

Here is more info on networking in Rasbian Stretch:
https://raspberrypi.stackexchange.com/a/37921

**Comment by XECDesign** [comment]
dhcpcd would refuse to run if anything is configured in /etc/network/interfaces.

**Comment by s1awa** [comment]
nothing is in /etc/network/interfaces

**Comment by XECDesign** [comment]
So networking wouldn't do anything.

**Comment by s1awa** [comment]
Yes networking should not do anything. But it prevented dhcpcd from setting static IP on boot until I disabled networking.
I am using my PI as dhcp server with pihole on my home network and don't have too much free time.
So I can't really mess around with the networking anymore to get some logs.

Hopefully the new dhcpcd version will solve those issues.
