### ISSUE TITLE
python{,3}-pifacecad packages are missing in Raspbian Stretch

### ISSUE THREAD

**Issue by DanielChesters** [RPi-Distro/repo#87]
Hi,

Since I upgrade to Raspbian Stretch, the package python-pifacecad and python3-pifacecad are missing. I already created an issue in piface/pifacecad repository (see piface/pifacecad#23).

**Comment by XECDesign** [comment]
These packages have been dropped because they are no longer maintained by OpenLX and don't work under Stretch.
