### ISSUE TITLE
Lirc: configuration loglevel

### ISSUE THREAD

**Issue by LIRCuser** [RPi-Distro/repo#91]
When trying to get lirc running with an IguanaIR transceiver I came accross the followig:

Loglevel is not configured with 'loglevel' in lirc_options.conf but with 'debug'.
Same in Debian source.

./lib/lirc_options.c
  line 49 and 180
  
Is this by design or is this a bug?

**Comment by XECDesign** [comment]
This seems like a question for the author or the software or the package maintainer. If it's a bug, it should be raised here:
https://www.debian.org/Bugs/Reporting
