### ISSUE TITLE
stretch: python3-lirc not installable

### ISSUE THREAD

**Issue by neonknight** [RPi-Distro/repo#94]
```
The following packages have unmet dependencies:
 python3-lirc : Depends: python3 (< 3.5) but 3.5.3-1 is installed
```

however, current python-lirc from pypi can easily be installed.

**Comment by XECDesign** [comment]
Thanks for the heads up.

@tompreston, is the answer here that people should use pypi instead?

**Comment by tompreston** [comment]
Hi, yeah I'm under the impression all Python packages should be installed using PyPi. I think this might be an error from piface-cad, which depends on python-lirc.

I think the installation instructions need updating.

**Comment by XECDesign** [comment]
Thank you
